### ISSUE TITLE
Use pwritev()

### ISSUE THREAD

**Issue by benbjohnson** [boltdb/bolt#238]
Use `pwritev()` when flushing data to disk so that we can batch multiple pages into a single syscall.

/cc @siddontang @pkieltyka

**Comment by pkieltyka** [comment]
hey guys, just wondering if this is on the radar, since it sounds like it can help with write performance?

**Comment by benbjohnson** [comment]
I haven't made any progress on this yet. It hasn't been much of a priority because I'm not sure how much it'll actually help performance. The main performance issue with random writes is that they amplify writes a ton. You likely end up getting throttled by disk write speed and not syscall invocation time.
