### ISSUE TITLE
Async Writes

### ISSUE THREAD

**Issue by benbjohnson** [boltdb/bolt#26]
Add an async flag to the `DB` to set whether writes are synchronous or asynchronous.

**Comment by akotlar** [comment]
Don't mean to reopen the issue, wanted to follow up on @tv42's comments that file systems do not preserve write order. Is this true? ext4 documentation explicitly states that it does (default data=ordered). 

https://www.kernel.org/doc/Documentation/filesystems/ext4.txt

**Comment by tv42** [comment]
```
data=ordered	(*)	All data are forced directly out to the main file
			system prior to its metadata being committed to the
			journal.
```

Nothing in that says write to data block A is done before write to data block B, just that both data block writes are done before the corresponding metadata is written to the journal.
