### ISSUE TITLE
Cursor behavor on modifications

### ISSUE THREAD

**Issue by freepk** [boltdb/bolt#260]
Hello.

https://gist.github.com/freepk/b4bfb0aacbc6e2a5f862

There are many situations when cursor's Prev() Next() don't return correct position or error after data change.
In this example cursor position after Seek is "testKey00". After delete "testKey00" and "testKey01", Next() return nil, but Prev() return "testKey02" how to understan this behavior?

**Comment by jrick** [comment]
Does this apply to any modifications made to any part of the database, or only when changes are made to the bucket the cursor is iterating over?

**Comment by benbjohnson** [comment]
@jrick It should only apply to the bucket that it is iterating over.
