### ISSUE TITLE
"invalid argument" when opening db

### ISSUE THREAD

**Issue by ktmn** [boltdb/bolt#272]
I got a new docker container "google/golang"

gopath/src/test contains this file, main.go:

    package main

    import (
    	"github.com/boltdb/bolt"
    	"log"
    )

    func main() {
    	db, err := bolt.Open("data.db", 0600, nil)
    	if err != nil {
    		log.Fatal(err)
    	}
    	defer db.Close()
    }

I do a 

    go get github.com/boltdb/bolt

and then in the gopath/src/test directory I run

    go run main.go

Result: 

    2014/12/29 01:51:34 invalid argument
    exit status 1

A 16kb data.db file is created.

go version go1.3.1 linux/amd64

---

Probably some rookie mistake. But it works on my Windows. So what am I missing?

**Comment by ktmn** [comment]
So the problem was indeed my mistake. I should have mentioned the way I ran the docker container was by mounting my files (first from Windows to VM, then) from VM to the docker container (basically I'm running docker on a virtual machine, just like boot2docker does it also)

    docker run -i -t -v /media/sf_go/src/test:/gopath/src/test google/golang /bin/bash

Here's what went down when compiling main.go according to strace if it tells anyone anything: http://pastebin.com/raw.php?i=CKWuMSHL

I guess bolt couldn't deal with the Windows file system as it was running on some form of Linux.

So I mounted to volume to another path, copied them over to gopath and things worked great.

**Comment by benbjohnson** [comment]
@ktmn Awesome! I'm glad to hear it worked out. As for the `strace`, nothing jumps out at me but thanks for posting it.

**Comment by pindamonhangaba** [comment]
This also happens when trying to open a database on a shared vagrant folder, with a Windows host.

**Comment by scotthelm** [comment]
Using Vagrant on a Mac host with a linux virtual, I experienced the same issue. I found that using nfs for the synched folders worked well.

    config.vm.synced_folder local_dev_dir, "/my/go/path", nfs: true, map_uid: 0, map_gid: 0

**Comment by ascotan** [comment]
BTW I ran into this issue on vagrant with bolt.  The problem is that a mmap'ed file can be run out of a shared folder with the options to mmap are MAP_SHARED.  strace reports the following:

```
stat("xxx.db", {st_mode=S_IFREG|0600, st_size=32768, ...}) = 0
open("xxx.db", O_RDWR|O_CREAT|O_CLOEXEC, 0666) = 3
flock(3, LOCK_EX|LOCK_NB)               = 0
fstat(3, {st_mode=S_IFREG|0600, st_size=32768, ...}) = 0
pread(3, "\0\0\0\0\0\0\0\0\4\0\0\0\0\0\0\0\355\332\f\355\2\0\0\0\0\20\0\0\0\0\0\0"..., 4096, 0) = 4096
fstat(3, {st_mode=S_IFREG|0600, st_size=32768, ...}) = 0
ftruncate(3, 32768)                     = 0
futex(0x609500, FUTEX_WAKE, 1)          = 1
fsync(3)                                = 0
mmap(NULL, 32768, PROT_READ, MAP_SHARED, 3, 0) = -1 EINVAL (Invalid argument)
flock(3, LOCK_UN)                       = 0
close(3)                                = 0
futex(0x609500, FUTEX_WAKE, 1)          = 1
write(1, "invalid argument\n", 17invalid argument
```
See here: http://man7.org/linux/man-pages/man2/mmap.2.html and here: http://stackoverflow.com/questions/18420473/invalid-argument-for-read-write-mmap

Basically you can't run a boltdb file out of a shared folder in a VM due to the way mmap is working.

**Comment by treeder** [comment]
I was getting this on Mac using Docker with a mounted volume (docker-machine), so I just downloaded the Docker for Mac Beta and it fixed it. https://www.docker.com/products/docker#/mac
