### ISSUE TITLE
ForEach for buckets

### ISSUE THREAD

**Issue by mibori** [boltdb/bolt#273]
Hello!
Is it possible to enumerate buckets in the bucket?
It would be good that bolt will have methods like:

``` go
func (b *Bucket) ForEach(fn func(k, b *Bucket) error) error { /* */ }
func (b *Tx) ForEach(fn func(k, b *Bucket) error { /* */ }
```

Wouldn't it be easier (more useful) to use a way of `[]byte` to `*Bucket` conversion?

**Comment by kalopsia** [comment]
Great! Thanks for the question and answer. I have the same issue) @benbjohnson I think it would be nice to add this information in the comments of `func (b *Bucket) ForEach(..)` declaration. Unfortunately, it isn't obvious(
