### ISSUE TITLE
wish list - support getting number of keys in a bucket in constant time

### ISSUE THREAD

**Issue by kmanley** [boltdb/bolt#276]
Currently the only ways to get the number of keys in a bucket is to traverse its keys or to call bucket.GetStats() which does some additional low-level stats gathering.

It would be nice if there were a way to get the number of keys in a bucket in constant time, given a bucket handle. One approach would be to store the number of keys in the bucket structure itself, accessible by a new bucket function e.g. GetNumKeys(). Of course the code would have to be careful to keep this value up to date.

**Comment by denys-potapov** [comment]
Probably you could define your own Bucket type, and count whatever you want

```golang
type CountableBucket struct {
	*bolt.Bucket
}

func (b *CountableBucket) NumOfKeys() uint64{
	return binary.Uvarint(b.Get([]byte("counter")))
}

func (b *CountableBucket) addCount(d uint64) {
	c = b.NumOfKeys()
	c += d
	b = make([]byte, 8, 8)
	binary.PutUvarint(b, c)
	b.Bucket.Put([]byte("counter"), b)
}

func (b *CountableBucket) Put(key []byte, value []byte) error {
	exists = b.Get(key) != nil
	
	err = b.Bucket.Put(key, value)
	if (err != nil) {
		return err
	}

	if (exists) {
		return nil
	}

	b.addCount(1)	
	return nil
}

func func (b *CountableBucket) Delete(key []byte) error {
	exists = b.Get(key) != nil
	
	err = b.Bucket.Delete(key)
	if (err != nil) {
		return err
	}

	if (exists) {
		return nil
	}

	b.addCount(-1)
	return nil	
}
```

**Comment by benbjohnson** [comment]
@kmanley Sorry for the delay in getting back to you. I thought about adding a key count to `Bucket` but the main issue was keeping it sync. It's so easy to miss one spot and then throw off the counter. At this point the file format is fixed so adding a count would be backwards incompatible.

Here's the current `bucket` header:

https://github.com/boltdb/bolt/blob/master/bucket.go#L52-L59

There's just not any wiggle room to push an `int64` counter in there.
