### ISSUE TITLE
SliceHeader

### ISSUE THREAD

**Issue by freepk** [boltdb/bolt#288]
Hello,

How do u think, can you lose memory allocated for SliceHeader(http://golang.org/pkg/reflect/#SliceHeader) in this code - https://github.com/boltdb/bolt/blob/master/db.go#L545?

WBR Paul.

**Comment by benbjohnson** [comment]
@freepk what's the error you're getting?

**Comment by freepk** [comment]
@benbjohnson there are no errors, make([]byte, ...) allocates two peaces of data, not in one block, first is SliceHeader, seconds array for data. You store information just about second part.
Example:
b := make([]byte, 16)

**Comment by davecgh** [comment]
There is no leak.  The buf variable goes out of scope at the end of the function, so there will no longer be any remaining references to the slice header and it becomes eligible for GC.

```Go
package main

import (
	"fmt"
	"runtime"
	"time"
	"unsafe"
)

func foo() unsafe.Pointer {
	b := make([]byte, 16)
	runtime.SetFinalizer(&b, func(b *[]byte) {
		fmt.Println("Released b...")
	})
	b[0] = 0x55
	return unsafe.Pointer(&b[0])
}

func main() {
	up := foo()
	runtime.GC()
	time.Sleep(1 * time.Second)
	fmt.Printf("up %p, first byte %x\n", up, (*[16]byte)(up)[0])
	time.Sleep(1 * time.Second)
}
```

Output:
> Released b...
> up 0xc082006280, first byte 55

**Comment by benbjohnson** [comment]
@davecgh is correct. Also, nice quick code write up. :)

We've been running Bolt with hundreds of allocate calls a second for months without restart. I'm confident that we don't have a memory leak issue during allocation.
