### ISSUE TITLE
Would be great to have a function to get a list of buckets

### ISSUE THREAD

**Issue by andre1s** [boltdb/bolt#295]

**Comment by kemist** [comment]
Hey Andre, this should get you a flat list of top level buckets. Taken from https://github.com/boltdb/bolt/blob/master/cmd/bolt/buckets.go

```go
// Buckets prints a list of all buckets.
func Buckets(path string) {
	if _, err := os.Stat(path); os.IsNotExist(err) {
		fmt.Println(err)
		return
	}

	db, err := bolt.Open(path, 0600, nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer db.Close()

	err = db.View(func(tx *bolt.Tx) error {
		return tx.ForEach(func(name []byte, _ *bolt.Bucket) error {
			fmt.Println(string(name))
			return nil
		})
	})
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

**Comment by benbjohnson** [comment]
@andre1s You can retrieve the bucket list from any `Bucket` by iterating over the keys and finding any key which has a `value` of `nil`. The Bolt API is already getting crowded so I'd prefer to not add additional methods if they're not necessary.
