### ISSUE TITLE
Calling NextSequence on a bucket without modifying the bucket loses the increment

### ISSUE THREAD

**Issue by MJDSys** [boltdb/bolt#296]
If a function calls NextSequence on a bucket without actually modifying the bucket, the increment is lost.  So, for instance the following code (where db is a *bolt.DB):
```
db.Update(func(tx *bolt.Tx) error {
    n, _ := tx.Bucket(bucket).NextSequence()
})
db.Update(func(tx *bolt.Tx) error {
    o, _ := tx.Bucket(bucket).NextSequence()
})
```
n and o will both hold the same value.  While it is an edge case, would it be possible/allowed to fix this so just calling NextSequence on a bucket still persists the change?

**Comment by benbjohnson** [comment]
Thanks for reporting the bug. It's fixed with this PR: https://github.com/boltdb/bolt/pull/297

**Comment by MJDSys** [comment]
Excellent, thanks for fixing this!
