### ISSUE TITLE
DB size grows on OS X

### ISSUE THREAD

**Issue by xlab** [boltdb/bolt#303]
Hello. I have OS X Yosemite 10.10.2 and go1.4.1 darwin/amd64, the situation is similar to #291. It seems that #292 fix works, because DB size grows exactly by 1GB at once. The problem is, the file grows on each `bolt.Open`, the initial size of DB was **3072MB**

```go
func main() {
	for i := 0; i < 100; i++ {
		db, _ := bolt.Open("file.db", 0644, nil)
		time.Sleep(time.Second)
		db.Close()
	}
}
```

After ~100 seconds I've got ~**103GB** file and no space left on the device.
`file resize error: truncate file.db: no space left on device`

I can tell more details upon request, just don't know what kind of details will be useful there.
Thanks.

**Comment by benbjohnson** [comment]
What commit SHA1 are you using? I ran your example using the latest (75f70a1) and it doesn't grow the database beyond the initial 1MB size.

**Comment by benbjohnson** [comment]
Ah, nm. I found it once I bumped the size high enough. Thanks. Will fix.

**Comment by xlab** [comment]
I'm using b8dbe1101d74c30e817227a99716591e3e6e6bc4 that's the last significant commit. My DB is 3072MB in size so maybe that matters. I need some time to reproduce that bug using abstract data, so will update  this issue later. As the most simple way, I can hand you my 3GB blob privately, but it's better to make a test case :) Stay tuned.

**Comment by kemist** [comment]
@xlab confirmed with https://gist.github.com/kemist/f2c4a6ded05fb6aeb98d

**Comment by kemist** [comment]
Oh nm, didn't see your confirm ben

**Comment by benbjohnson** [comment]
@xlab @kemist: Fixed: https://github.com/boltdb/bolt/pull/304

**Comment by benbjohnson** [comment]
CI is :green_heart: but can one of you confirm the fix before I merge it?

**Comment by kemist** [comment]
Hey Ben, you are fast! Confirmed, db no longer grows

**Comment by benbjohnson** [comment]
:dancer:

**Comment by xlab** [comment]
Thanks!
