### ISSUE TITLE
README Prefix scan example nil derefs

### ISSUE THREAD

**Issue by tv42** [boltdb/bolt#307]
```go
    for k, v := c.Seek(prefix); bytes.HasPrefix(k, prefix); k, v = c.Next() {
        fmt.Printf("key=%s, value=%s\n", k, v)
    }
```

k == nil happens. Maybe make that

```go
    for k, v := c.Seek(prefix); k != nil && bytes.HasPrefix(k, prefix); k, v = c.Next() {
        fmt.Printf("key=%s, value=%s\n", k, v)
    }
```

just like the later Range scan has.

**Comment by benbjohnson** [comment]
Is this to prevent an infinite loop if `len(prefix) == 0`? `bytes.HasPrefix()` should work fine with a `nil` `k` otherwise.

http://golang.org/src/bytes/bytes.go?s=7986:8023#L323

**Comment by tv42** [comment]
Right. I was being stupid.
