### ISSUE TITLE
advice for bulk loading

### ISSUE THREAD

**Issue by skybrian** [boltdb/bolt#312]
The README says:

"Bulk loading a lot of random writes into a new bucket can be slow as the page will not split until the transaction is committed. Randomly inserting more than 100,000 key/value pairs into a single new bucket in a single transaction is not advised."

This says what not to do, but I'm wondering what to do instead.

I'm thinking of using boltdb to create a read-only index. That is, create an empty file, write a lot of data to it, close it, copy the database file to a production server, and from then on it's read-only. If I need to update it, I'll build a new file from scratch.

The data starts out in random order and I expect it to be larger than physical RAM. I can fairly easily buffer small batches of incoming data if needed. Would sorting each batch before writing it work better? Should I write each sorted batch in a separate write transaction? Would it be better to create child buckets using a prefix of the keys?

(And is boltdb recommended for this use case at all?)

**Comment by benbjohnson** [comment]
If you know you're going to use Bolt as a read-only database then your best option is to sort your entire dataset and set `Bucket.FillPercent = 1` on every `Bucket` you write into. Bolt normally leaves room in a page after it splits to allow room for new writes without causing page splits. But if you are writing everything in sorted order then you don't need that.

However, if you can't sort the entire dataset then I would recommend sorting each batch and keeping batches relatively small -- 1K - 10K each. You'll have to play around with the batch size to see how it works with your data distribution.

Ultimately, though, Bolt might not be the best option. I think it should work fine but you may get more performance out of using an encoding like [Cap'n Proto](https://capnproto.org/) or [FlatBuffers](http://google.github.io/flatbuffers/) that let you mmap a read-only data file. Then you wouldn't have any transactional overhead and it'd be more-or-less raw structs you're accessing. If the data file is larger than memory then the OS will handle paging in and out data with its LRU cache.
