### ISSUE TITLE
freelist tests fails for 32 bits ARCH

### ISSUE THREAD

**Issue by poffe** [boltdb/bolt#316]
```
GOARCH=386 go test -run 'TestFreelist.*'
```
gives me:
```
# github.com/boltdb/bolt
./freelist.go:164: type [2147483647]pgid larger than address space
./freelist.go:164: type [2147483647]pgid too large
./freelist.go:168: type [2147483647]pgid larger than address space
./freelist.go:168: type [2147483647]pgid too large
./freelist.go:193: type [2147483647]pgid larger than address space
./freelist.go:193: type [2147483647]pgid too large
./freelist.go:196: type [2147483647]pgid larger than address space
./freelist.go:196: type [2147483647]pgid too large
./freelist.go:197: type [2147483647]pgid larger than address space
./freelist.go:197: type [2147483647]pgid too large
./freelist.go:197: too many errors
FAIL	github.com/boltdb/bolt [build failed]
```

**Comment by poffe** [comment]
Seems like lowering the constant maxAllocSize in page.go from ```0x7FFFFFFF``` to ```0x9FFFFFF``` makes the tests pass but I have no clue what impact this would have.

**Comment by benbjohnson** [comment]
Thanks for reporting. I reverted the `maxAllocSize` for the `386` architecture only in this PR: https://github.com/boltdb/bolt/pull/317

Can you test that out and verify that it fixes the issue?

**Comment by poffe** [comment]
Yes, I can confirm that PR #317 fixes the issue. Thanks for the quick turnaround.

**Comment by benbjohnson** [comment]
:+1: merging

**Comment by poffe** [comment]
Sorry, but I forgot to test it in my ARM architecture (which is 32-bits as well) before confirming the pull request. I guess the ```maxAllocSize``` constant is needed in ```bolt_arm.go``` as well?
I'm getting this as ```go test``` result on my ARM:
```
# github.com/boltdb/bolt
./freelist.go:164: undefined: maxAllocSize
./freelist.go:164: invalid array bound maxAllocSize
./freelist.go:168: undefined: maxAllocSize
./freelist.go:168: invalid array bound maxAllocSize
./freelist.go:193: undefined: maxAllocSize
./freelist.go:193: invalid array bound maxAllocSize
./freelist.go:196: undefined: maxAllocSize
./freelist.go:196: invalid array bound maxAllocSize
./freelist.go:197: undefined: maxAllocSize
./freelist.go:197: invalid array bound maxAllocSize
./freelist.go:197: too many errors
FAIL	github.com/boltdb/bolt [build failed]
```

**Comment by Oliv4945** [comment]
I added "maxAllocSize" in bolt_arm.go to be able to compile it on arm, but maybe we should open another issue ?

**Comment by poffe** [comment]
Great! And yes, I guess we should but I can't do it right now due to personal reasons.

**Comment by Oliv4945** [comment]
Done https://github.com/boltdb/bolt/issues/320 ;)
