### ISSUE TITLE
Freelist build fails on ARM architecture

### ISSUE THREAD

**Issue by Oliv4945** [boltdb/bolt#320]
```go test``` on an ARM architecture fails:
```
# github.com/boltdb/bolt
./freelist.go:164: undefined: maxAllocSize
./freelist.go:164: invalid array bound maxAllocSize
./freelist.go:168: undefined: maxAllocSize
./freelist.go:168: invalid array bound maxAllocSize
./freelist.go:193: undefined: maxAllocSize
./freelist.go:193: invalid array bound maxAllocSize
./freelist.go:196: undefined: maxAllocSize
./freelist.go:196: invalid array bound maxAllocSize
./freelist.go:197: undefined: maxAllocSize
./freelist.go:197: invalid array bound maxAllocSize
./freelist.go:197: too many errors
FAIL    github.com/boltdb/bolt [build failed]
```
I copy/paste the declaration from ```bolt_386.go``` file to ```bolt_arm.go``` and it works, but I am not sure about the value to use...

```
// maxAllocSize is the size used when creating array pointers.
const maxAllocSize = 0xFFFFFFF
```

This issue follow https://github.com/boltdb/bolt/issues/316

**Comment by skirmish** [comment]
I had submitted a PR (https://github.com/boltdb/bolt/pull/319) that fixes the compiler error, this was accepted and merged a few hours ago.

**Comment by poffe** [comment]
👍

**Comment by Oliv4945** [comment]
Great thanks, and sorry, I search on issues but not pull request...
By the way, how do you select the value ? Thx
