### ISSUE TITLE
bolt bench --stats-interval not working

### ISSUE THREAD

**Issue by mbertschler** [boltdb/bolt#322]
I am seeing strange output of bolt bench used with --stats-interval
Am I using it wrong? I just updated with go get -u and run it on OSX 10.10.2

    $ bolt bench --value-size 128 --stats-interval "3s" --count 300000 --write-mode "rnd"
	{"FreePageN":0,"PendingPageN":0,"FreeAlloc":0,"FreelistInuse":0,"TxN":0,"OpenTxN":0,"TxStats":{"PageCount":0,"PageAlloc":0,"CursorCount":0,"NodeCount":0,"NodeDeref":0,"Rebalance":0,"RebalanceTime":0,"Split":0,"Spill":0,"SpillTime":0,"Write":0,"WriteTime":0}}
	{"FreePageN":0,"PendingPageN":0,"FreeAlloc":0,"FreelistInuse":0,"TxN":0,"OpenTxN":0,"TxStats":{"PageCount":0,"PageAlloc":0,"CursorCount":0,"NodeCount":0,"NodeDeref":0,"Rebalance":0,"RebalanceTime":0,"Split":0,"Spill":0,"SpillTime":0,"Write":0,"WriteTime":0}}
	...
	{"FreePageN":0,"PendingPageN":0,"FreeAlloc":0,"FreelistInuse":0,"TxN":0,"OpenTxN":0,"TxStats":{"PageCount":0,"PageAlloc":0,"CursorCount":0,"NodeCount":0,"NodeDeref":0,"Rebalance":0,"RebalanceTime":0,"Split":0,"Spill":0,"SpillTime":0,"Write":0,"WriteTime":0}}
	{"FreePageN":0,"PendingPageN":2,"FreeAlloc":8192,"FreelistInuse":32,"TxN":-1,"OpenTxN":0,"TxStats":{"PageCount":23356,"PageAlloc":95666176,"CursorCount":300003,"NodeCount":2,"NodeDeref":138468,"Rebalance":0,"RebalanceTime":0,"Split":23350,"Spill":23355,"SpillTime":537339106,"Write":23357,"WriteTime":155897728}}
	# Write	1m39.797195649s	(332.657us/op)	(3006 op/sec)
	# Read	1.005595961s	(52ns/op)	(19230769 op/sec)

**Comment by benbjohnson** [comment]
The `stats-interval` was meant to dump out the `DB.Stats` as JSON periodically. It's not terribly useful so I'll likely just remove it. :)
