### ISSUE TITLE
bolt cmd has no put

### ISSUE THREAD

**Issue by anacrolix** [boltdb/bolt#323]
It seems useful to have various put and other altering commands with the bolt binary, but these aren't provided.

**Comment by benbjohnson** [comment]
Closing this one as the `bolt` CLI is meant for debugging purposes only. The application should handle the write format.

**Comment by anacrolix** [comment]
It would be helpful to be able to explore the contents of a bolt files without having to write application code. The cmd/bolt could have put and get that read/write to stdin and stdout, and list the contents of buckets. Example:
```
$ bolt bolt.db get completed # completed is a bucket
a
b

$ bolt bolt.db get completed/a
contents of a

$ bolt bolt.db put completed/a <<< 'new contents'
$ bolt bolt.db get completed/a
new contents
```
