### ISSUE TITLE
bucket.Put() should call cloneBytes() consistently on the Key and Value

### ISSUE THREAD

**Issue by cep21** [boltdb/bolt#324]
The documentation inside "Caveats & Limitations" contains 

    Byte slices returned from Bolt are only valid during a transaction

This documents slices used during reads.  It is also true that the slices passed to a bolt transaction are required to be valid for the entire transaction.

I attempted to memory optimize my code by reusing the same byte slice inside a transaction and doing Put() operations with it.  This did not work.  Maybe it would be good to clarify the Caveats & Limitations or the documentation for Put() to mention that the slice passed must be untouched for the duration of the transaction.

**Comment by cep21** [comment]
I looked more into this and it may be a bug.  You call cloneBytes() inside bucket.Put() on the value, but do not on the key.

**Comment by davecgh** [comment]
I wholeheartedly disagree.  In fact, I think it was a mistake for the key to be copied too.  I don't want the ability to avoid additional copies taken away from me as a caller who is in need of efficient use.  The API should document that it has zero-copy semantics and the caller must be careful to not reuse/modify the data.

I understand why it's convenient, but the caller can make a copy if they so desire.  When you shove it into the Put function, the caller no longer has the opportunity to avoid the copy and that is bad for performance.

**Comment by cep21** [comment]
I don't have a big opinion either way.  I also would like it if the bytes were just pointers, but then I need some kind of guarantee about when it's safe to reuse the buffer I've passed in.  Is it safe to reuse when the transaction is over?  Or maybe the contract is that I can't reuse the buffer ever?  It also makes sense to be consistent about how the bytes of the key and value are treated, rather than only calling copy on one.

I hope it doesn't sound like I'm splitting hairs, but contracts on how I can use the []byte I pass into Put() both key and value are important for optimizing my code.

**Comment by tv42** [comment]
I'd vote for less copying, more exact documentation of the assumptions. Transaction scope seems sane.

This does make Put different from e.g. Write. But Get is already different from Read, I think that's ok.

**Comment by artyom** [comment]
I would also like this to be more clearly specified in `Put` function documentation — this would have saved me at least an hour of figuring out what's happening. It would be great if documentation warn against reusing byte slice passed to `Put` so we can avoid [usage attempts like this one](https://gist.github.com/artyom/805ae04bfa4ae2f8df10):

```
	err = db.Update(func(tx *bolt.Tx) error {
		bkt, err := tx.CreateBucketIfNotExists([]byte("one"))
		if err != nil {
			return err
		}
		buf := make([]byte, 10)
		for i := int64(0); i < 3; i++ {
			n := binary.PutVarint(buf, i)
			if err := bkt.Put(buf[:n], buf[:n]); err != nil {
				return err
			}
		}
		return nil
	})
```

**Comment by chrsm** [comment]
Only the key is copied, the value is not currently copied:

    ...
    func (b *Bucket) Put(key []byte, value []byte) error {
    	...
    
    	// Move cursor to correct position.
    	c := b.Cursor()
    	k, _, flags := c.seek(key)
    
    	// Return an error if there is an existing key with a bucket value.
    	if bytes.Equal(key, k) && (flags&bucketLeafFlag) != 0 {
    		return ErrIncompatibleValue
    	}
    
    	// Insert into node.
    	key = cloneBytes(key)
    	c.node().put(key, key, value, 0, 0)
    
    	return nil
    }

The value must be valid for the duration, not the key. (Just wanted to clarify here)
