### ISSUE TITLE
User group/mailing list/forum

### ISSUE THREAD

**Issue by baijum** [boltdb/bolt#331]
It would be great if there is a place to ask questions about Bolt. I think there are enough number users to create a group/mailing list/forum. Google groups would be good place.

**Comment by benbjohnson** [comment]
I think a mailing list is a good idea. I've used Google Groups before and it's ok. I don't love it. I posted a message on Twitter asking for other suggestions.

https://twitter.com/benbjohnson/status/578546523778109440

If I don't hear of anything better in a couple days then I'll create a Google Group.
