### ISSUE TITLE
Batching inserts does not improve performance and increases disk space usage

### ISSUE THREAD

**Issue by alexsacr** [boltdb/bolt#337]
A benchmark performed [here](https://sacrilege.io/benchmarking-bolt/) showed inserting 500k records in batches of 1000 did not increase write performance compared to performing individual transactions.  In addition, batching inserts doubled the file size of the resulting DB on disk.

The dataset consisted of a constant string value (`"877.11"`), and a sequentially increasing string key beginning at an arbitrary unix timestamp (`"1427323829"`).

Sequential insertions were performed by calling `db.Update()` with a single key-value combination:

```
db.Update(func(tx *bolt.Tx) error {
    bkt := tx.Bucket([]byte(bucketName))
    err := bkt.Put([]byte(key), []byte(value))
    return err
})
```

Batch insertions were made via slices (ignoring the array allocation issue here):

```
func batchInsert(db *bolt.DB, keys []string, value string) {

	if len(keys) < batchSize {
		insertSlice(db, keys, value)
		return
	}

	numKeys := len(keys)
	batches := len(keys) / batchSize
	offset := numKeys - (numKeys % batchSize)

	for i := 0; i < batches; i++ {
		insertSlice(db, keys[i:(i+1)*1000], value)
	}

	if offset != 0 {
		insertSlice(db, keys[offset:], value)
	}

}

func insertSlice(db *bolt.DB, keys []string, value string) {

	db.Update(func(tx *bolt.Tx) error {
		bkt := tx.Bucket([]byte(bucketName))
		for _, k := range keys {
			err := bkt.Put([]byte(k), []byte(value))
			if err != nil {
				panic(err)
			}
		}
		return nil
	})

}
```

If you don't spot anything glaringly wrong with my use of Bolt, the code used to run the benchmark can be found [here](https://github.com/alexsacr/bolt-benchmark).  

To grab the code and run only the insertion benchmarks (one with individual transactions, one with batches of 1k), something like this ought to work:

```
git clone https://github.com/alexsacr/bolt-benchmark.git
cd bolt-benchmark/
go test -bench=500k
```

**Comment by tv42** [comment]
Those keys are not sequentially increasing, they are stringified integers and thus spread fairly evenly.

**Comment by tv42** [comment]
Batch size of 10k speeds up Benchmark500kBatchInsert 10x.

**Comment by dtfinch** [comment]
I haven't run it yet, but I think the first call to insertSlice is missing a multiplication, causing it to insert very large batches.

insertSlice(db, keys[i\***batchSize**:(i+1)*batchSize], value)

**Comment by alexsacr** [comment]
Bah, you're right @dtfinch.  One bug I'm ok with, but this benchmark is misleading.  I'm going to close out this case and pull down the post until I get it right.

**Comment by benbjohnson** [comment]
@tv42 @dtfinch Good eyes. :) I glanced at the code yesterday but didn't catch those. I'm adding some docs on Sequential vs Rrandom Writes and on `bolt bench` per #338.

**Comment by xiang90** [comment]
@benbjohnson I ran `bench` test on my SSD local machine. There is not much performance difference if the batch-size is 1 between random and sequential.(There is huge difference when the batch size is large) Is that expected? If the batch size is 1, no matter what the change will modify the entire tree path?

**Comment by benbjohnson** [comment]
@xiang90 Yes, the leaf page and its parent branches all have to be written to disk along with a meta page and the freelist whenever a transaction is committed. Sequential batched writes amortize that cost per write because many of the writes share the same leaf and parent branch pages. That's why there's such a stark difference.
