### ISSUE TITLE
README.md bug

### ISSUE THREAD

**Issue by DSpeichert** [boltdb/bolt#339]
```cannot use func literal (type func(bolt.Tx) error) as type func(*bolt.Tx) error in argument to db.View```
in the example of database backups:
```go
func BackupHandleFunc(w http.ResponseWriter, req *http.Request) {
    err := db.View(func(tx bolt.Tx) error {
```

**Comment by benbjohnson** [comment]
Thanks for the notice. If you PR a change I'll can merge it. Otherwise I can change it on my side.
