### ISSUE TITLE
Wait to close DB if there are open transactions

### ISSUE THREAD

**Issue by timshannon** [boltdb/bolt#341]
This is probably an enhancment request, as I don't believe this behavior was unintentional, but you can open a DB, open a transaction, then close the DB.

```
package main

import (
	"fmt"
	"os"

	"github.com/boltdb/bolt"
)

func main() {
	// Open the database.
	db, _ := bolt.Open("test.db", 0666, nil)
	defer os.Remove(db.Path())

	// Start a write transaction.
	db.Update(func(tx *bolt.Tx) error {
		// Create a bucket.
		tx.CreateBucket([]byte("widgets"))
		b := tx.Bucket([]byte("widgets"))

		// Set the value "bar" for the key "foo".
		b.Put([]byte("foo"), []byte("bar"))

		// Retrieve the key back from the database and verify it.
		value := b.Get([]byte("foo"))
		fmt.Printf("The value of 'foo' was: %s\n", value)
		return nil
	})

	// Retrieve the key again.
	tx, _ := db.Begin(false)

	db.Close()
	value := tx.Bucket([]byte("widgets")).Get([]byte("foo"))
	if value == nil {
		fmt.Printf("The value of 'foo' is now: nil\n")
	}
}
```

The documention says that the value from the bucket is valid while the transaction is open, and in my mind, I see db.Close() as a kind of *safe shutdown*. 

There is a timeout option already for the db Open call, why not use the same timeout on Close, and wait for any currently open transactions to finish?

The copy on write nature of Bolt means you'll never have partially committed data, so the issue isn't one of integrity, but your client can end up with a panic.

**Comment by benbjohnson** [comment]
I thought there was an open issue for this already but I'm looking back through the issues and I don't see one. This is definitely annoying since it can cause a panic. You're correct that it won't cause corruption though. I'll try to throw a PR together soon.

**Comment by alaska** [comment]
Chiming in to suggest that Close() should wait on outstanding Batch() calls, too.  Seems like a ```waitgroup``` would be a perfect way to handle this.

**Comment by benbjohnson** [comment]
Sorry for the delay. Added support for a blocking close here: https://github.com/boltdb/bolt/pull/377

**Comment by benbjohnson** [comment]
I didn't add `Batch()` blocking because I wanted to make sure I got the basic use case working first.
