### ISSUE TITLE
No flush when DB.NOSYNC == true

### ISSUE THREAD

**Issue by rakoo** [boltdb/bolt#343]
When you know you're going to put many keys, it can be interesting to put the db in NOSYNC mode, push the changes, then flush to make sure everything is written, excet there is no flush method and all the `fdatasync` are hidden. Does `DB.Close()` flush the data ?

**Comment by benbjohnson** [comment]
The `DB.Close()` doesn't flush the data. I kinda wish `NoSync` wasn't in there. You're better off batching and letting the database sync on its own.
