### ISSUE TITLE
Possible deadlock introduced since v1.0 release

### ISSUE THREAD

**Issue by timshannon** [boltdb/bolt#344]
I'm running into an issue where occasionally some deletes I'm running seem to just hang indefinitely right on the call to `tx.Bucket([]byte("bucketname")).Delete(key)`.

I have yet to build a repeatable, stand-alone piece of code, as this seems to happen after a certain amount of activity.

I can trigger activity that will cause the deadlock pretty easily though, and I've confirmed that the issue doesn't show up with the v1.0 release.  I'm backtracking through the commits now to try and fine the specific one that is causing my issue.

I'm on Linux (Ubuntu 14.04).  I've wrapped my delete calls with a timer to spit out the stack trace if they didn't finish for 20 seconds, so we could see where to go routine is waiting. I'll add more details as I find them, and see if I can build you something repeatable, but until then here's the stack trace to look at:

```
goroutine 44 [semacquire]:
sync.(*RWMutex).Lock(0x187665c4)
        /usr/local/go/src/sync/rwmutex.go:87 +0x97
github.com/boltdb/bolt.(*DB).mmap(0x18766500, 0x401000, 0x0, 0x0)
        /home/tshannon/workspace/go/src/github.com/boltdb/bolt/db.go:188 +0x52
github.com/boltdb/bolt.(*DB).allocate(0x18766500, 0x2, 0x82a867f, 0x0, 0x0)
        /home/tshannon/workspace/go/src/github.com/boltdb/bolt/db.go:599 +0x12a
github.com/boltdb/bolt.(*Tx).allocate(0x188e8b00, 0x2, 0x0, 0x0, 0x0)
        /home/tshannon/workspace/go/src/github.com/boltdb/bolt/tx.go:397 +0x43
github.com/boltdb/bolt.(*Tx).Commit(0x188e8b00, 0x0, 0x0)
        /home/tshannon/workspace/go/src/github.com/boltdb/bolt/tx.go:162 +0x351
github.com/boltdb/bolt.(*DB).Update(0x18766500, 0x1882dafc, 0x0, 0x0)
        /home/tshannon/workspace/go/src/github.com/boltdb/bolt/db.go:512 +0x127
bitbucket.org/tshannon/freehold/data/store.(*DS).Delete(0x18732bd0, 0x18726d00, 0x43, 0xc1, 0x0, 0x0)
        /home/tshannon/workspace/go/src/bitbucket.org/tshannon/freehold/data/store/store.go:280 +0xc5
bitbucket.org/tshannon/freehold/data.(*CoreDS).Delete(0x1870ae60, 0x8356d80, 0x1870bb20, 0x0, 0x0)
        /home/tshannon/workspace/go/src/bitbucket.org/tshannon/freehold/data/coreds.go:87 +0xa3
bitbucket.org/tshannon/freehold/ratelimit.ResetLimit(0x18737ca0, 0xe, 0x841e448, 0xe, 0x0, 0x0)
        /home/tshannon/workspace/go/src/bitbucket.org/tshannon/freehold/ratelimit/ratelimit.go:94 +0x137
main.authenticate(0xf7503800, 0x18c89b20, 0x18c89a40, 0x8409a08, 0x0, 0x0)
        /home/tshannon/workspace/go/src/bitbucket.org/tshannon/freehold/auth.go:120 +0xb7c
main.propertiesGet(0xf7503800, 0x18c89b20, 0x18c89a40)
        /home/tshannon/workspace/go/src/bitbucket.org/tshannon/freehold/properties.go:28 +0x59
main.(*methodHandler).ServeHTTP(0x1872e5f0, 0xf7503800, 0x18c89b20, 0x18c89a40)
        /home/tshannon/workspace/go/src/bitbucket.org/tshannon/freehold/routes.go:169 +0x1e9
bitbucket.org/tshannon/treemux.(*Mux).ServeHTTP(0x18732300, 0xf7503800, 0x18c89b20, 0x18c89a40)
        /home/tshannon/workspace/go/src/bitbucket.org/tshannon/treemux/mux.go:225 +0x126
net/http.serverHandler.ServeHTTP(0x18728280, 0xf7503800, 0x18c89b20, 0x18c89a40)
        /usr/local/go/src/net/http/server.go:1703 +0x145
net/http.(*conn).serve(0x18753440)
        /usr/local/go/src/net/http/server.go:1204 +0x9d8
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x2ce
```

**Comment by timshannon** [comment]
Found my issue.  I was running Commit on my read only transaction, and not handling the error properly, so I was left with several open transactions.

I might send a pull request for a slight documentation change on how you need to rollback a read only transaction instead of commit it.

Thanks,

**Comment by benbjohnson** [comment]
Thanks for diving into this and debugging the issue. Documentation PRs are always appreciated!

It might be better to panic when committing a read-only `Tx`. Technically it would break backwards compatibility but I can't imagine that there's any code out there that's intentionally committing read-only transactions.
