### ISSUE TITLE
Allowing db files under 1MB

### ISSUE THREAD

**Issue by mcuadros** [boltdb/bolt#350]
I am using bolt as storage engine for [raa](https://github.com/mcuadros/go-raa), since is a general purpose archive format, in some cases the contained files could be less than 1MB.

I wish know if this bootstrapping size can be configured on some way per database, allowing db files under 1MB. This change could have performance impact, due to the continues growing mmap?

Thanks!

**Comment by chrsm** [comment]
@benbjohnson Looks like this one can be closed with #351 fixed.

**Comment by benbjohnson** [comment]
:+1:
