### ISSUE TITLE
Hangs on linux ubuntu but not on windows 7

### ISSUE THREAD

**Issue by oknoorap** [boltdb/bolt#359]
It's weird, on windows my code works perfectly, but on ubuntu it wil hangs up for inifinite time,
My codes:

```
package main

import (
	"fmt"
	"log"
	"github.com/boltdb/bolt"
	"time"
)

func main() {

	db, err := bolt.Open("./engine.db", 0600, &bolt.Options{Timeout: 2 * time.Second})
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte("settings"))
		v := b.Get([]byte("config"))
		fmt.Printf("Config is: %s\n", v)
		return nil
	})

	adb, err := bolt.Open("./engine.db", 0600, &bolt.Options{Timeout: 2 * time.Second})
	if err != nil {
		log.Fatal(err)
	}
	defer adb.Close()
	adb.View(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte("settings"))
		v := b.Get([]byte("config"))
		fmt.Printf("Config is: %s\n", v)
		return nil
	})
}
```

**Comment by oknoorap** [comment]
or it will be timeout:
```
2015/04/27 05:31:05 timeout
exit status 1
```

**Comment by benbjohnson** [comment]
You'll need to close the database before you reopen it. The defer on the first close won't execute until the end of main() so the second Open() executes before the first db is closed.

**Comment by benbjohnson** [comment]
The reason it doesn't hang on Windows is because Windows doesn't have advisory locking so it won't block. However, it's not safe to execute two DB instances of the same file concurrently.

**Comment by oknoorap** [comment]
I know, but I need it when use in different file, e.g when I'm working on different routers, 

> I need to open bucket "settings", then I'm open bucket "posts" in different files
> I stores db variable on struct, and then benchmarking with apache benchmark 1000 request and 32 concurency, it will not consistence, http server will closed, and refused connection

any solution?
