### ISSUE TITLE
Best way to implement replication 

### ISSUE THREAD

**Issue by mbertschler** [boltdb/bolt#361]
What would be the best way to implement replication for bolt? I am thinking mostly about master/slave replication, where in the event of a server failure the second machine can take over without any downtime.

I searched for the available functions and found `func (tx *Tx) OnCommit(fn func())` but I would not know which keys have changed so I could replicate this changes to the slave. Currently im thinking that the only way to implement this would be to write a wrapper around `Tx`.

I am glad if someone could give me pointers on how they use bolt in use cases that require fault tolerance. Thanks!

**Comment by benbjohnson** [comment]
@mbertschler Fault tolerance / HA is a much bigger topic and depends a lot on your requirements. You can get strong consistency by using a consensus protocol (e.g. Paxos, Raft) but there are also other approaches that use weak consistency. It's a fairly complicated problem so unfortunately the only suggestion I can make is to read some research papers. :-/

https://github.com/papers-we-love/papers-we-love
https://raftconsensus.github.io/
http://thesecretlivesofdata.com/raft/

**Comment by mbertschler** [comment]
@benbjohnson thank you for these tips. This interactive guide http://thesecretlivesofdata.com/raft/ makes it pretty easy to understand.

**Comment by unirep** [comment]
@mbertschler Did you get anywhere with Bolt replication? If not, is there another solution anyone is aware of?

**Comment by mbertschler** [comment]
@unirep no I did not take this further. Bolt and a fully distributed database are quite different things. 
An interesting article to read about this is the [CochroachDB design document](https://github.com/cockroachdb/cockroach/blob/master/docs/design.md).
They are using RocksDB (different storage architecture but similar to Bolt) as a storage engine, and built their distributed database as a layer on top of that.

I personally have a use case where there is a central server cluster, and many nodes that are distributed over a wide area and not in the same datacenter, you could call that setup IoT. I use Bolt as a database on these external nodes, and CockroachDB in the central server cluster. For this I am implementing my own asynchronous replication. The software on the node can work standalone with just Bolt, but the central server database is used for backup and remote access.

I don't know about your use case but maybe this database could work for you: [tidwall/summitdb](https://github.com/tidwall/summitdb) (also in Go), I haven't tried it though.

**Comment by vincent-petithory** [comment]
@unirep As others mentionned, this is a vast and complex topic.
You may want to take a look at [rbolt](https://github.com/vincent-petithory/rbolt) which provides some building blocks (like a journal buffer) for something that might suit your needs.
