### ISSUE TITLE
Add db.Sync() api

### ISSUE THREAD

**Issue by xiaost** [boltdb/bolt#364]
hello, @benbjohnson 
In my project, I need something like "sync every second"
boltdb only provides `db.NoSync` option, 
Eh...I can do it by committing an empty tx with `db.NoSync = true` every second :cry: 
It looks good to add `db.Sync()` api, right?

**Comment by benbjohnson** [comment]
Added `DB.Sync()` to https://github.com/boltdb/bolt/pull/366. Can you take a look and verify that's what you're looking for?

**Comment by xiaost** [comment]
Yeah, exactly what I need. :+1: :laughing:

**Comment by benbjohnson** [comment]
Cool, it's merged. :+1:
