### ISSUE TITLE
Connection Pool

### ISSUE THREAD

**Issue by raunakspecial1994** [boltdb/bolt#386]
Bolt obtains a file lock on the data file so multiple processes cannot open the same database at the same time. Opening an already open Bolt database will cause it to hang until the other process closes it.

As this is the case,is there any connection pooling concept like various clients connecting and accessing the database at the same time.? Is this possible in boltdb?

**Comment by benbjohnson** [comment]
Bolt is meant to exist at a lower level than network protocols. LMDB provides multi-process database access but at the cost of additional complexity. What's your use case?

**Comment by raunakspecial1994** [comment]
There are various unique id and all are bidding a amount at a rate of milliseconds and i have to store it and update their current spend(spend till that particular time) as soon as possible.
The schema i am using is like -making a bucket for every unique id and storing the time as the key and value as the bid.
and then making a common bucket for all unique and updating their current spend in that
where key=unique id and value = latest current spend .

So how can i update the common bucket as fast as possible .
all the buckets are in the same database.

**Comment by benbjohnson** [comment]
You should be able to get that kind of performance if you use `bolt.DB.Batch()`. It would all need to run through a single process though.
