### ISSUE TITLE
HasSuffix not working during the key scans

### ISSUE THREAD

**Issue by 6D65** [boltdb/bolt#393]
Hi,

I've stumbled upon this strange behaviour while using the library. There's the example in the documentation, that shows how to iterate all the keys in the db and find ones with a certain prefix.
```go
db.View(func(tx *bolt.Tx) error {
    c := tx.Bucket([]byte("MyBucket")).Cursor()

    prefix := []byte("1234")
    for k, v := c.Seek(prefix); bytes.HasPrefix(k, prefix); k, v = c.Next() {
        fmt.Printf("key=%s, value=%s\n", k, v)
    }

    return nil
})
```
I've tried to search by suffix based on this example. And it just won't work.
```go
db.View(func(tx *bolt.Tx) error {
    c := tx.Bucket([]byte("MyBucket")).Cursor()

    suffix := []byte("1234")
    for k, v := c.Seek(suffix); bytes.HasSuffix(k, suffix); k, v = c.Next() {
        fmt.Printf("key=%s, value=%s\n", k, v)
    }

    return nil
})
```

So i've tried to debug this and did a search by all the keys, and checked all the results. And there were indeed keys that had this suffix. I wonder if anyone can reproduce this, and what may cause this.

```go
db.View(func(tx *bolt.Tx) error {
    c := tx.Bucket([]byte("MyBucket")).Cursor()

    suffix := []byte("1234")
    for k, v := c.Seek(suffix); k != nil; k, v = c.Next() {
        fmt.Printf("Found : %x | Searched For Suffix : %x | Is it a suffix? : %t", k, p, bytes.HasSuffix(k, suffix))
    }

    return nil
})
```

Thanks

**Comment by dtfinch** [comment]
Keys are sorted, and Seek() goes to the first key matching the prefix. The loop exits on the first result not matching the suffix. Unless all your keys with that suffix are contiguous in the sorted list, and having the same suffix as a prefix, you can't expect that for() loop to work.

Finding all the matching suffixes would require a slower full scan (or changing your keys, or using another bucket as an index, etc.): 

    for k, v := c.First(); k != nil; k, v = c.Next() {
        if bytes.HasSuffix(k, suffix) {
            fmt.Printf("key=%s, value=%s\n", k, v)
        }
    }

**Comment by benbjohnson** [comment]
@dtfinch is correct, if you use stringified numbers then they'll be sorted in the bucket like this:

```
1
10
11
12
2
3
4
5
6
7
8
9
```

If you want to store a numeric value as a key and filter it then I'd recommend using `binary.BigEndian.PutUint64()`:

```go
myNumericKey := 123456
key := make([]byte, 8)
binary.BigEndian.PutUint64(key, myValue)

tx.Bucket([]byte("MyBucket")).Put(key, []byte("some value"))
```

Then the number will always be in order in your cursor. Also, it's important to note that little endian doesn't work as the byte order is inverted and Bolt sorts on simple byte order.

**Comment by 6D65** [comment]
Cool, thank you.

I'm not yet using numeric values. Will keep this in mind. For now will do as suggested and go through all the keys each time and find the ones I need. Will try to think of something better if there will be performance issues.
