### ISSUE TITLE
select from id >= 5 and <= 10 

### ISSUE THREAD

**Issue by spx** [boltdb/bolt#394]
how can i do that? :) \\∞

**Comment by benbjohnson** [comment]
You can find an [example of a range scan in the README](https://github.com/boltdb/bolt#range-scans). It ranges over dates but integers work the same way. You'll need to make sure you use something like `binary.BigEndian.PutUint64()` to encode your integer keys though.

**Comment by spx** [comment]
range scan - yes. but how about binary tree for auto increment seq? 
1 2 3 4 5 10 25 \\∞
id >= 6 
or only one way are full table scan while i find my id and then limit \\∞

**Comment by benbjohnson** [comment]
The `Cursor.Seek()` uses Bolt's b+tree to quickly move to the beginning. You'll need to check on every subsequent key if it is less than your max value in your range.
