### ISSUE TITLE
Batch Operations in Boltdb

### ISSUE THREAD

**Issue by raunakspecial1994** [boltdb/bolt#395]
how can i use Batch operations in boltdb  ? 
Any Working example.

**Comment by benbjohnson** [comment]
@raunakspecial1994 `DB.Batch()` works the same as `DB.Update()`. Just pass it a function that'll be executed in the context of a transaction. Bolt handles grouping multiple functions together into a single transaction.

The one caveat is that you have to call `DB.Batch()` from multiple goroutines for it to be effective (such as from multiple requests on an HTTP server). It's a blocking call so calling it in a loop will mean that it'll have to wait for one transaction to execute before it can get called again.
