### ISSUE TITLE
Transaction Commit: 'fatal error: all goroutines are asleep - deadlock!'

### ISSUE THREAD

**Issue by sebtzm** [boltdb/bolt#397]
In my project I have code that deletes key from bucket, when Commit is called it stays and never returns.

I have discovered that it remains stuck in function: 
_func (db *DB) mmap(minsz int) error_ 
of db.go, when it is called:

db.mmaplock.Lock()

Bolt file **db.go**

     // mmap opens the underlying memory-mapped file and initializes the meta references.
     // minsz is the minimum size that the new mmap can be.
     func (db *DB) mmap(minsz int) error {
   
	    fmt.Println("before db.mmaplock.Lock()---------------")
	    db.mmaplock.Lock() //HANG HERE
	    fmt.Println("NEVER PRINT THIS LINE---------------")
	    defer db.mmaplock.Unlock()
	    ...

**Comment by sebtzm** [comment]
I tried to reproduce error.
Mistakenly I'm going to delete a key inside a View transaction. Ok I know that is my fault.
	  
Following code is a sample that I have written for reproduce the error.
In this case I have: **'fatal error: all goroutines are asleep - deadlock!'**
always at same line *'db.mmaplock.Lock()' (bolt/db.go:213)*

Bolt should explicitly return error at commit.

This sample code just inserts three keys in one bucket, after iterates over bucket and for every bucket iterates its keys and delete them. First deletion goes ok, second I have a fatal deadlock.

    package main
    
    import (
    	"fmt"
    	"strconv"
    	"time"
    	"github.com/boltdb/bolt"
    )
    
    // DB ...
    var DB *bolt.DB
    
    //IterateFunc ...
    type IterateFunc func(key string, value string) error
    
    func main() {
    	counter := -1
    
    	for {
    		counter++
    		
    		var err error
    		DB, err = bolt.Open("demo.db", 0600, &bolt.Options{Timeout: 1 * time.Second})
    		if err != nil {
    			fmt.Println("Error:", err)
    			return
    		}
    		defer DB.Close()
    		
    		if (counter % 2) != 0 { //insert only when counter is odd
    			for i := 0; i < 3; i++ {
    				insertKey("bucket", "Sample Key"+strconv.Itoa(i), "value"+strconv.Itoa(i))
    			}
    		}
    		
    		if (counter % 2) == 0 { //delete keys only when counter is even
    			iterateOverBucketAndKeys(deleteKey) //pass function 'deleteKey' to iterateOverBucketAndKeys.
    		}
    		
    		fmt.Printf("Wait %v seconds...Zzz...\n", 3)
    		time.Sleep(time.Duration(3) * time.Second)
    	} //end for
    	
    }
    
    func insertKey(bucket string, key string, value string) error {
    
    	fmt.Println("Insert Key:", key)
    
    	return DB.Update(func(tx *bolt.Tx) error {
    		b, dErr := tx.CreateBucketIfNotExists([]byte(bucket))
    		if dErr != nil {
    			return fmt.Errorf("create bucket: %s", dErr)
    		}
    		pErr := b.Put([]byte(key), []byte(value))
    		if pErr != nil {
    			return pErr
    		}
    		return nil
    	})
    }
    
    func iterateOverBucketAndKeys(iterFn IterateFunc) (err error) {
    
    	err = DB.View(func(tx *bolt.Tx) error {
    
    		tx.ForEach(func(name []byte, b *bolt.Bucket) error {
    
    			c := b.Cursor()
    
    			for k, v := c.First(); k != nil; k, v = c.Next() {
    				iErr := iterFn(string(k), string(v))
    				if iErr != nil {
    					fmt.Println("iterFn error:", iErr)
    				}
    			} //for
    
    			return nil
    		}) //end for each bucket
    
    		return nil
    	}) //end view
    
    	return
    }
    
    func deleteKey(key string, value string) error {
    	fmt.Println("1. Key:", key)
    
    	tErr := DB.Update(func(tx *bolt.Tx) error {
    		fmt.Println("2.")
    
    		b := tx.Bucket([]byte("bucket"))
    
    		fmt.Println("3.")
    
    		if b == nil {
    			fmt.Println("5.")
    			return nil
    		}
    
    		fmt.Println("6. Try to delete key...")
    
    		dErr := b.Delete([]byte(key))
    		if dErr != nil {
    			fmt.Println("7.", dErr)
    			return dErr
    		}
    
    		fmt.Println("8.", "Return from 'DB.Update' for commit...")
    		return nil
    	})
    
    	fmt.Println("9.")
    
    	if tErr != nil {
    		fmt.Println("10. Commit Error:", tErr)
    		return tErr
    	}
    
    	fmt.Println("11. Commit Ok.")
    	
    	return nil
    }

**Comment by chrsm** [comment]
Hi sebtzm,

Currently, at the "top level" of your code, you are getting a timeout because `defer DB.Close()` does not execute until `main` returns.

Furthermore, there's a deadlock as you're running `deleteKey` (which executes in the context of a writeable transaction) inside of a read-only transaction (`iterateOverBucketAndKeys`). Nested transactions are not supported in BoltDB - see #404.

**Comment by sebtzm** [comment]
Hi chrsm,

Yes, I understand that it was my fault.

Maybe BoltDb should return something like:

     errors.New("Write not allowed in read-only transaction")

even just to avoid that users like me have to report this issue ;-)

**Comment by chrsm** [comment]
Well, Bolt does actually do that (see: https://github.com/boltdb/bolt/blob/master/bucket.go#L277) but you're (basically) attempting to nest transactions - which aren't supported. The writing transaction is blocked until the read is done, but as the read depends on the write finishing, you get a deadlock.

In other words, there's no way for the update (`deleteKeys`) to start executing and no way for the read to complete. You'd need to do something like:

* start read tx
* read keys, appending to a slice what you want to delete
* finish read tx
* start write tx
* delete keys that you tracked
* finish write tx

@benbjohnson I think this one should be closed as there is no bug here.

**Comment by sebtzm** [comment]
In function ```deleteKeys``` var ```tErr``` is **never** equal to ```ErrTxNotWritable```.

**Comment by chrsm** [comment]
@sebtzm Right, because in `deleteKey` (when it actually runs) it's a writable transaction. But you cannot run the `deleteKey` function inside of the read-only transaction, as it must wait until the read-only one is complete - and the read-only one is *waiting* for some kind of return from `deleteKey`. So you get a deadlock. :)

**Comment by sebtzm** [comment]
It is perfectly clear that I can not write in a read transaction. I have already fixed my code two week ago.
The code posted is deliberately wrong to show that I do not receive any error in ``tErr``.
I expected to receive an error, now I kwnow that can have only fatal deadlock. 
Thank You.
