### ISSUE TITLE
Bolt tagging

### ISSUE THREAD

**Issue by aviau** [boltdb/bolt#399]
Hello!

Sorry if this is not an issue.

Are you still tagging bolt? The last release dates Nov 27, 2014

**Comment by benbjohnson** [comment]
I haven't been tagging Bolt although I should probably start doing it again. I'm starting to work through the issues again so once I get some of those fixed then I'll tag a v1.1.0 release.

**Comment by benbjohnson** [comment]
I added a v1.1.0 tag.
