### ISSUE TITLE
Large CPU usage in (*pgids).Less

### ISSUE THREAD

**Issue by cep21** [boltdb/bolt#406]
Hi,

I'm using bolt on a large read heavy database that is currently around 8GB in size.  When I CPU profile my go application I see the following:

```
(pprof) top4
9.27s of 30.72s total (30.18%)
Dropped 440 nodes (cum <= 0.15s)
Showing top 4 nodes out of 216 (cum >= 1.48s)
      flat  flat%   sum%        cum   cum%
     4.90s 15.95% 15.95%      4.90s 15.95%  github.com/boltdb/bolt.(*pgids).Less
     1.71s  5.57% 21.52%      6.86s 22.33%  sort.doPivot
     1.41s  4.59% 26.11%      1.41s  4.59%  github.com/boltdb/bolt.func·004
     1.25s  4.07% 30.18%      1.48s  4.82%  runtime.mallocgc
```

Is there something I can do or some tweak I can make to reduce the time spent sorting pgids?

**Comment by benbjohnson** [comment]
@cep21 What commit are you using? @mkobetic added a performance fix for freelist updates in https://github.com/boltdb/bolt/pull/391.

**Comment by cep21** [comment]
Doeh.  Forgot to include that as well.  I am using 2c04100eb9793f2b8541d243494e2909d2112325.  We're doing a code push this week and I'll update to 04a3e85793043e76d41164037d0d7f9d53eecae3.  I'll update the task with any performance changes we see then.

After reading the diff, it's my understanding I won't need to delete and repopulate my old bolt database to see the improvement.  Is that correct?

**Comment by benbjohnson** [comment]
Yes, that's correct. The file format for bolt is fixed and won't change in the future either. It should always be safe upgrade to later commits of bolt.

**Comment by funny-falcon** [comment]
look to #408 , i've made custom sort for pgids for the same issue

**Comment by cep21** [comment]
Using 04a3e85793043e76d41164037d0d7f9d53eecae3 removed the sort from pprof top30!  Awesome!
