### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by drsnyder** [boltdb/bolt#416]
`bolt` is a dependency of [`influxdb`](https://github.com/influxdb/influxdb/blob/master/LICENSE_OF_DEPENDENCIES.md). I tried building a simple file that depends on the influxdb client and it's failing with bolt compile errors. It looks like the source of the error is coming from this [PR](https://github.com/boltdb/bolt/pull/414).

**Comment by benbjohnson** [comment]
Are you building with Go 1.4.x?

**Comment by drsnyder** [comment]
Yes, `go version` produces: `go version go1.4.2 darwin/amd64`.

**Comment by benbjohnson** [comment]
Hmm, I'm trying to use build tags because Go 1.4 doesn't recognize `arm64` as a `GOARCH` but that doesn't seem to be working: https://github.com/boltdb/bolt/pull/417

I'm going to revert the arm64 change until I can get this figured out.

**Comment by benbjohnson** [comment]
Can you verify the removal works for you on Go 1.4? https://github.com/boltdb/bolt/pull/418

**Comment by drsnyder** [comment]
Yup. Works fine now. Thanks!
