### ISSUE TITLE
Tests cannot run on 32 bit platforms

### ISSUE THREAD

**Issue by raggi** [boltdb/bolt#420]
```
.\bucket_test.go:653: len argument too large in make([]byte)
```

This should probably have a build flagged 32-bit value for such platforms.

**Comment by benbjohnson** [comment]
@raggi Can you try changing `MaxValueSize` to `(1<<31)-1` and try running it? I'll just drop down that value if that works on `windows 386`.

**Comment by raggi** [comment]
Because of the way that the line is written in the test, it needs to be (1<<31)-2 in order to make space for a test slice to be larger than MaxValueSize in order for the error to be returned.

**Comment by benbjohnson** [comment]
Fixed via https://github.com/boltdb/bolt/pull/447
