### ISSUE TITLE
Example of nextSequence usage

### ISSUE THREAD

**Issue by rogierlommers** [boltdb/bolt#436]
I'm trying to replace sqlite with bolt for my personal, fun project. However, I'm having trouble with auto increment the keys. Would it be possible to provide a very simple example which makes use of the nextSequence() function?

I have found this great post: http://bl.ocks.org/joyrexus/22c3ef0984ed957f54b9
But unfortunately, the used ID's are not generated by bolt. And if I understand correct, this IS possible by using NextSequence(), right?

**Comment by benbjohnson** [comment]
Yes, Bolt can generate autoincrementing sequences. The sequences are attached to the buckets as a matter of convenience but you can use the resulting value however you'd like.

Given a data type like:

```
type User struct {
	ID int
	...
}
```

Typically the usage looks something like:

```
type Store struct {
	db *bolt.DB
}

// CreateUser saves u to the store.
// The new user ID is set on u once the data is persisted.
func (s *Store) CreateUser(u *User) error {
	return s.db.Update(func(tx *bolt.Tx) error {
		// Retrieve the users bucket.
		// This should be created when the DB is first opened.
		b := tx.Bucket([]byte("users"))
		
		// Generate ID for the user.
		// This returns an error only if the Tx is closed or not writeable.
		// That can't happen in an Update() call so I ignore the error check.
		id, _ = b.NextSequence()
		u.ID = int(id)

		// Marshal user data into bytes.
		buf, err := json.Marshal(u)
		if err != nil {
			return err
		}

		// Persist bytes to users bucket.
		return b.Put(itob(u.ID), buf)
	})
}

// itob returns an 8-byte big endian representation of v.
func itob(v int) []byte {
	b := make([]byte, 8)
	binary.BigEndian.PutUint64(b, uint64(v))
	return b
}
```

**Comment by rogierlommers** [comment]
Thanks for your feedback; will check it out.
