### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by tianon** [boltdb/bolt#438]
It's been a bit since v1.0 now; any chance we could get a new release tag with some of the improvements made since then? :smile:

(Maybe including #431 so we get more compilation targets too? :innocent:)

**Comment by brahmaroutu** [comment]
@benbjohnson What do you think about providing us with a tag? Docker seem to prefer using tags to pull the code instead of commit ids.

**Comment by tianon** [comment]
For sure, especially since it lightens the burden on our packagers who have
to package Git snapshots if there aren't official releases of a dependency.
:smile: :heart:

**Comment by thaJeztah** [comment]
ping @benbjohnson :heart:

**Comment by brahmaroutu** [comment]
@benbjohnson Please let us know your thoughts on this. We are waiting to see if we can get version tag on this. Not necessarily a major version change but some point in time tag to process. ex: v1.1 ?

**Comment by benbjohnson** [comment]
I added a [v1.1.0](https://github.com/boltdb/bolt/releases/tag/v1.1.0) tag on the latest commit with release notes for everything changed since `v1.0`.

**Comment by brahmaroutu** [comment]
@benbjohnson Thanks a lot.

**Comment by thaJeztah** [comment]
Thanks @benbjohnson, much appreciated!
