### ISSUE TITLE
is cursor loop sorted ascending with fmt.Sprint(b.NextSequence) ?

### ISSUE THREAD

**Issue by xtaci** [boltdb/bolt#448]
is cursor loop sorted ascending with fmt.Sprint(b.NextSequence) ?

**Comment by xtaci** [comment]
what if i store big-endian uint64  as key?

**Comment by benbjohnson** [comment]
The cursor iterates in sorted byte order so `binary.BigEndian.PutUint64()` works great but `fmt.Sprint()` will not.

You can do descending order if you use `Last()`/`Prev()` on the cursor instead of `First()`/`Next()`.

**Comment by xtaci** [comment]
Yes, I've tried <code>binary.BigEndian.PutUint64()</code>, it works as expected.
