### ISSUE TITLE
Is it possible to access a remote BoltDB file?

### ISSUE THREAD

**Issue by everdev** [boltdb/bolt#449]
Hi, is it possible to host the .db files one server and query them from another?  In other words, having an app sit on a computationally efficient server and the .db files on a high storage server.  Thanks.

**Comment by benbjohnson** [comment]
@everdev You could use NFS to attach a disk over the network but I'm not sure what kind of guarantees NFS provides around `fsync` & `mmap`. There's not currently a native network protocol for bolt though.
