### ISSUE TITLE
Question: transaction logging (not WAL)

### ISSUE THREAD

**Issue by lmb** [boltdb/bolt#458]
Hi,

I'm currently trying to figure out what the best way to create transaction logs would be. This is not about improving write performance, but for replicating changes to remote BoltDBs. I want to do the following:

1. Write snapshot of DB to client with Tx.WriteTo
2. Keep client up to date by sending transaction logs (essentially Puts and Deletes and a "version" field)

Ideally I'd be able to pair this with using DB.Batch, and prevent Tx's from committing if the transaction log could not be written. My current working hypothesis is that I will have to create a custom version of DB.Batch, and accept that there is trickery involved in dealing with a txlog that has data from an aborted Tx. Is there a more elegant way that I'm missing?

Your help is much appreciated!

Edit: maybe this should be called command logging instead? See [this SO answer](http://stackoverflow.com/questions/14181180/).

**Comment by benbjohnson** [comment]
@lmb You'll probably need to wrap the Bolt types with something of your own. Something like:

```go
package mypkg

type Bucket struct {
	*bolt.Bucket

	path [][]byte      // parent keys to traverse to bucket
	txlog *bolt.Bucket // top-level transaction log.
}

func (b *Bucket) Put(k, v []byte) error {
	// Write to target bucket.
	if err := b.Bucket.Put(k, v); err != nil {
		return err
	}

	// Append to transaction log.
	seq, _ := b.txlog.NextSequence()
	entry := encodeTxlogEntry("put", b.path, k, v)
	if err := b.txlog.Put(seq, entry); err != nil {
		return err
	}

	return nil
}
```

You'll need to do the other methods too (`Delete()`, `Bucket()`, `CreateBucket()`, etc). That should give you a single `txlog` bucket that sequentially stores all your changes. You should be able to wrap `DB.Batch()` as well.
