### ISSUE TITLE
Coalescer is gone?

### ISSUE THREAD

**Issue by rhcarvalho** [boltdb/bolt#465]
The README says:

> Bolt is good for read intensive workloads. Sequential write performance is also fast but random writes can be slow. You can add a write-ahead log or [transaction coalescer](https://github.com/boltdb/coalescer) in front of Bolt to mitigate this issue.

But the link https://github.com/boltdb/coalescer is broken as of now. Old issues make me believe the repository has existed in the past, but is not there anymore.

**Comment by benbjohnson** [comment]
The coalescer repo was removed a while ago when @tv42 added `DB.Batch()`. I fixed the README: https://github.com/boltdb/bolt/pull/467

**Comment by rhcarvalho** [comment]
Thanks @benbjohnson!
