### ISSUE TITLE
bolt.Open returns non-standard error

### ISSUE THREAD

**Issue by rhcarvalho** [boltdb/bolt#468]
In [db.Open](https://github.com/boltdb/bolt/blob/b34b35ea8d06bb9ae69d9a349119252e4c1d8ee0/db.go#L192), instead of returning a standard error from `errors.go`, the validation error is wrapped with `fmt.Errorf`, which makes it harder to write code that handles specific errors.
I see that it is probably to help with debugging, as the validation error can happen in page "meta0" or "meta1".

I'd like to be able to write code like so:

```go
	db, err := db.Open("my.db")
	switch err {
	case bolt.ErrChecksum:
		// handle err...
	case bolt.ErrInvalid:
		// handle err...
	case bolt.ErrVersionMismatch:
		// handle err...
	}
```

That wouldn't be necessary if there was a clear way to check that a file is a valid database. Checking `err.String() == "meta0 error: invalid database"` doesn't look good.

**Comment by benbjohnson** [comment]
@rhcarvalho I agree. If you want to PR a fix then I'll merge it in.

**Comment by rhcarvalho** [comment]
@benbjohnson thanks, I'll send one when I get a chance.
