### ISSUE TITLE
Transaction with multiple databases

### ISSUE THREAD

**Issue by diegobernardes** [boltdb/bolt#475]
There is any way to use transactions with multiple databases?
Of if this is not possible, there is some restriction to develop this feature?

I'm doing a study about databases and implementing a toy project around boltdb.

**Comment by benbjohnson** [comment]
Multi-`DB` transactions are not possible. You may be able to implement something similar to 2-phase commit but that seems overly complicated. Bolt can have nested buckets so another option is to simply make each top-level bucket a different database.
