### ISSUE TITLE
Provide helper methods for most common data types

### ISSUE THREAD

**Issue by jacek99** [boltdb/bolt#488]
The need for manual conversion to []byte on every call is really annoying boilerplate after a while.

Would it be possible to add helper methods to all the APIs for the most common types such as string, int64, etc

e.g.

CreateBucketString(bucket string)
PutString(key string, value []byte)

etc

Just some API enhancements to avoid the constant []byte cast every time.

**Comment by peter-edge** [comment]
I'm working on auto-generating these, I was going to file an issue about it when done and seeing if there's any interest in adding it mainline: https://github.com/peter-edge/boltutil-go

**Comment by peter-edge** [comment]
@jacek99 it's mostly "done, I did move it to https://github.com/peter-edge/bolttype-go (but original link will work, it's a repo rename). https://go.pedge.io/bolttype works too.

`bolttype.DB` is a complete wrapper for `bolt.DB`, except adds auto-generated functions to/from all pairs of:

[]byte
string
uint16
uint32
uint64
pair(uint16,uint16)
pair(uint32,uint32)
pair(uint64,uint64)
pair(uint16,[]byte)
pair(uint32,[]byte)
pair(uint64,[]byte)
pair([]byte,uint16)
pair([]byte,uint32)
pair([]byte,uint64)

**Comment by benbjohnson** [comment]
@jacek99 I agree that it's annoying to convert to `[]byte` all the time. I think that adding helper functions for the different types will make the API explode and make the `godoc` nearly unusable. The types used are very application dependent so I think keeping them in a separate repo works better and users can `import` or copy them to their application directly.

Personally, I typically use `int` or `uint64` for keys so i'll have helper functions like:

```
func u64tob(v uint64) []byte
func btou64([]byte) uint64
``` 

Then for `values` I typically use protobuf encoding so it ends up being `[]byte` anyway.

**Comment by peter-edge** [comment]
But it would be nice to just have this immediately available for common primitives, no? If the naming is consistent, it doesn't matter too much how the godoc looks, ie (from what I just did):

https://godoc.org/go.pedge.io/bolttype - unusable, no questions there
`GetUint64ToBytes(key uint64) []byte` - consistent, I know what function to call
`ForEachUint64ToBytes(fn func(key uint64, value []byte) error) error` - consistent

I also did pairs for some values, see https://github.com/peter-edge/bolttype-go/blob/master/bolttype_test.go

I'd love to just add this as a subpackage at `github.com/boltdb/bolt/type` if you were open to it.

**Comment by benbjohnson** [comment]
@peter-edge I think it adds too much complexity, especially since it requires adding new `DB`, `Bucket`, and `Tx` structs. I think simple `xtob()` functions (e.g. `i64tob()`) provide the same benefits without requiring the generation of so much code.

**Comment by jacek99** [comment]
I think you should at least provide support for string out of the box (both for keys and values as well as a combinatio). That should cover at least 80% of common usage IMHO.

**Comment by benbjohnson** [comment]
@jacek99 There's a bunch of different cases even for `string`. For example, do you want string keys and string values, or just string keys and `[]byte` values? Also, how do you indicate an unset key when the value is `string`? With `[]byte` an unset value is `nil` and an empty set value is `[]byte{}`.

I've had other people complain that the API is already too large (which I somewhat agree with). I don't feel like adding more functions for syntactic sugar is worth the API clutter.

**Comment by peter-edge** [comment]
I'd argue that for primitives with a non-nil zero value, you can do (type,
bool) as the return value, similar to maps. But I think we have the answer
for this issue :)
