### ISSUE TITLE
Synchronization clarification request

### ISSUE THREAD

**Issue by Kulak** [boltdb/bolt#493]
Based on what I've read in documentation I expect that only one update callback is executed at a time on each database file regardless of any other conditions.  I just want to make sure I am on the right track.

Is it guaranteed that each BoltDB update callback function will be called in a **synchronous** manner?

For example, if only one function can execute at the time, then the following code shall be able to create unique keys.  However, if for some reason update serialization is not guaranteed, then current time might not be the best way to create a unique key:

	db.Update(func(tx *bolt.Tx) error {
		key, err := time.Now().MarshalBinary()
		if err != nil {
			return err
		}

		b := tx.Bucket([]byte(MessagesKey))
		err = b.Put(key, value)
		return err
	})

Thank you

**Comment by benbjohnson** [comment]
Yes, callbacks from `Update()` are serialized so only one can operate at a time.

However, another option for generating unique, autoincrementing keys is to use `Bucket.NextSequence()`:

```
db.Update(func(tx *bolt.Tx) error {
    b := tx.Bucket([]byte(MessagesKey))

    seq, err := b.NextSequence()
    if err != nil {
    	return err
    }

    key := make([]byte, 8)
    binary.BigEndian.PutUint64(key, seq)

    if err := b.Put(key, value); err != nil {
    	return err
    }

    return err
})
```

**Comment by Kulak** [comment]
Thank you.  I wish the was some "forum" to ask questions instead of opening an Issue.

**Comment by benbjohnson** [comment]
Issues work well because they end up being indexed by Google. There's also a #boltdb room on the Gopher Slack: https://gophersinvite.herokuapp.com/
