### ISSUE TITLE
Performance: Sequential/append writes slow down a lot for larger buckets 

### ISSUE THREAD

**Issue by mkobetic** [boltdb/bolt#497]
We're seeing this with large bulk imports that we're doing when rebuilding our traffic databases. We're importing the values already presorted in sequential order so this should be a true append-only style workload. For smaller buckets < 1M values this is going quite nicely, but larger buckets seem to slow down disproportionately. The profile seems to point at [this spot](https://github.com/boltdb/bolt/blob/master/node.go#L132)

<img width="427" alt="screen shot 2016-01-25 at 9 30 26 am" src="https://cloud.githubusercontent.com/assets/871693/12555064/56b7f7de-c34d-11e5-960f-801b980322e3.png">

It looks like we're spending inordinate amount of time appending to the inodes slice, so I'm guessing preallocating some capacity may yield some nice speed up. I'm also thinking that this is probably more of an issue for branch nodes rather than leaf nodes. Our values are about 750 bytes on average so we only fit about 5 per leaf page, but the branch nodes are packed pretty tightly. We're running with bucket fill percent set to 0.9 to get better space utilization.

So I'm wondering what could be a sufficiently generic capacity preallocation scheme. If we do this for branch nodes only and assume that average key size is let's say 20 bytes, we might be able to get away with a simple ballpark constant (e.g. pagesize / key size * fill percent). Otherwise we could monitor the key counts on branch pages at runtime and slowly improve the preallocation based on the real data. But that can get a bit more involved.

Anyway, it should be quite easy to come up with a synthetic benchmark proving my conjectures, so I should have more than just handwaving to support any code changes, but if anyone has some thoughts, comments, please share.

Here are some bolt stats from one of our DBs (~10G), although this isn't one of the slow ones, most parameters should be similar just and order of magnitude or so larger. I'm still running bolt stats on a  bigger one, I'll post an update if I eventually get the results:

```
Page count statistics
	Number of logical branch pages: 32593
	Number of physical branch overflow pages: 0
	Number of logical leaf pages: 2266974
	Number of physical leaf overflow pages: 6702
Tree statistics
	Number of keys/value pairs: 11660687
	Number of levels in B+tree: 7
Page size utilization
	Bytes allocated for physical branch pages: 133500928
	Bytes actually used for branch data: 108434708 (81%)
	Bytes allocated for physical leaf pages: 9312976896
	Bytes actually used for leaf data: 7587024076 (81%)
Bucket statistics
	Total number of buckets: 4877
	Total number on inlined buckets: 761 (15%)
	Bytes used for inlined buckets: 446303 (0%)
```

**Comment by mkobetic** [comment]
I should add this is running go version go1.5.3 linux/amd64

**Comment by benbjohnson** [comment]
@mkobetic Yeah, that seems like an insane amount of time to spend on `memmove()`. Are there existing values in the buckets that have keys are higher than the ones you're inserting? Also, I'd be interested in seeing how performance changes if you add preallocations in your vendored code.

**Comment by mkobetic** [comment]
This is filling an empty DB with pre-sorted data, so this should be truly append only workload. I haven't instrumented the code to prove that beyond doubt but, I'm fairly confident about it (we were writing unsorted data earlier by accident and it was a LOT slower, to the point that it wouldn't finish in any reasonable time).

I will try patching our vendored code for our case, that's definitely the easiest way to confirm whether it will make much difference. I'll keep you posted.

BTW, we're somewhat behind with our bolt version, currently at https://github.com/boltdb/bolt/commit/04a3e85793043e76d41164037d0d7f9d53eecae3. I'll bring us up to date as well, but I don't expect that to make much difference with this issue.

**Comment by mkobetic** [comment]
Actually on second thought, it may not be true append after all. If you remember we're truncating the  session timestamps to 24hrs to help associating later pageviews with the initial ones (I keep forgetting about that). So while we're dutifully sorting the sessions based on their timestamp, that's not going to be the same order as the one implied by the actual DB keys (which is truncated time + session key) :facepalm:.

I can close the issue right now, or we can keep it open a little longer until I confirm that the problem is on my end. Thanks for clueing me in! :)

**Comment by benbjohnson** [comment]
@mkobetic I remember the truncated session timestamps vividly. :) Were you able to verify the sorting?

**Comment by mkobetic** [comment]
@benbjohnson not yet, I made the code changes, but struggled with odd test failures and lack of time this week. I expect to have an answer either tomorrow or early next week.

**Comment by mkobetic** [comment]
OK, after actually sorting the values the same way they are sorted in the DB the import's running at 7x the speed and the profile is much more even. I'd still say the random insert profile is suspiciously lopsided, but I don't whether anyone particularly cares about that scenario, so I'm happy to close this issue.

Just for a bit of context here if anyone cares, I was importing about 2B values across 64 separate bolt DBs on a 16 core box with 128G RAM and 3.5T of SSD storage (4 disks in RAID1). The badly sorted run took over 50 hours, once the rows were sorted correctly it dropped down to ~7.5hrs. The resulting total DB size was  ~1.7T. Again this was with FillPercent set to 0.9 which resulted in ~80% space utilization in the DB.

**Comment by benbjohnson** [comment]
@mkobetic The nodes don't split until they're spilled to disk and the children of a `node` are a simple sorted slice so what can happen is if you randomly insert a bunch of data into a single node then it'll have to keep shifting the slice so it can insert the data.

This normally isn't a problem since the slices are usually small but if you have large transactions with a bunch of values in one node then it can get quite expensive.

**Comment by mkobetic** [comment]
OK, that clarifies what was happening in this case. The chunks we're importing are fairly large (anywhere from 1-8M values depending on a partition) and committed in single transaction so we're probably creating giant nodes that were constantly shifting around their contents to accommodate the random inserts. So random inserts => small transactions, got it.

That also adjusts my assumptions about branches vs leaf nodes. Since after commit we can usually fit about 5 values in one 4K leaf page, I thought most of that overhead was in the branch nodes, but if leaf nodes split on commit as well, then it was more likely the leaf nodes that were copying very large chunks of memory over and over again. I can totally see that being very expensive.

Thanks for the insights!
