### ISSUE TITLE
reverse foreach on bucket

### ISSUE THREAD

**Issue by Kulak** [boltdb/bolt#502]
It would be nice to have a convenience method that iterates from Last to First.

**Comment by chrsm** [comment]
Do cursors not work for you?

    c := b.Cursor()
    for k, v := c.Last(); k != nil; k, v = c.Prev() {
        fmt.Printf("key=%X, value=%X\n", k, v)
    }

**Comment by Kulak** [comment]
Yes, that's what I use right now.

**Comment by Kulak** [comment]
No plan to enhance is fine by me.

**Comment by benbjohnson** [comment]
@Kulak I've found that many people are confused by `ForEach()` vs `Cursor`. I actually wish that I hadn't added `ForEach()` in the first place. I don't want to add `ReverseForEach()` because I feel like it will confuse users further and it clutters the API.
