### ISSUE TITLE
Copying Database Files cross-platform

### ISSUE THREAD

**Issue by DavidVorick** [boltdb/bolt#503]
Is it save in Bolt to copy a database file that way made on say, Lin64 to a Win32 platform? This is related to user support - we want to give our users an in-use database. The database will be created on a Linux64 machine, and then will be distributed with the binaries to all other major platforms. I want to make sure that there won't be any problems from transplanting a database file that was made on a particular architecture.

**Comment by benbjohnson** [comment]
Yes, it's safe to copy files across different OSes. The architecture only needs to have the same endianness.
