### ISSUE TITLE
tx.CopyFile fails on on windows/amd64

### ISSUE THREAD

**Issue by fawick** [boltdb/bolt#506]
When running the following small program on windows/amd64...
```go
package main

import "log"
import "github.com/boltdb/bolt"

func main() {
	db, err := bolt.Open("my.db", 0600, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	err = db.Update(func(tx *bolt.Tx) error {
		b, err := tx.CreateBucketIfNotExists([]byte("MyBucket"))
		if err != nil {
			return err
		}
		return b.Put([]byte("answer"), []byte("42"))
	})
	if err != nil {
		log.Fatal("filling db", err)
	}
	err = db.View(func(tx *bolt.Tx) error {
		return tx.CopyFile("my_copy.db", 0600)
	})
	log.Println("copy file:", err)
}
```

... I receive the following error:
`copy file: meta copy: read my.db: The process can not access the file because another process has locked a portion of the file.`

**Comment by benbjohnson** [comment]
@fawick I'm working on getting a Windows CI server up and running so I can get better test coverage for Windows machines. If Windows won't allow another file handle open while the process owns a write file handle then we may need to reuse `db.file`. However, that will mean that writes will block while the database is being copied.

**Comment by ChrisHines** [comment]
On Windows `os.OpenFile` opens files with `FILE_SHARE_READ | FILE_SHARE_WRITE`, which normally allows opening the file multiple times by multiple processes. But 1cb787ee7bfebef44baf98158967a37735e65790 added code to to call [`LockFileEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365203(v=vs.85).aspx) to acquire a lock on the file that does prevent subsequent opens—even by the same process.

However, this line from the MSDN docs for `LockFileEx` offers a possible work around:

>Locking a region of a file does not prevent reading from a mapped file view.

Could bolt use its mapped file view as the source of data written to the new file?

**Comment by ChrisHines** [comment]
A less safe alternative is to add this code to the top of `Tx.WriteTo`:

```go
	if runtime.GOOS == "windows" {
		funlock(tx.db.file)
		defer flock(tx.db.file, !tx.db.readOnly, 0)
	}
```

Which at least allows several tests to pass that currently fail on Windows. The tests that this issue cause to fail are: TestTx_CopyFile, TestTx_CopyFile_Error_Meta, and TestTx_CopyFile_Error_Normal.

**Comment by ChrisHines** [comment]
All of the tests mentioned above now pass on Windows.

**Comment by benbjohnson** [comment]
@ChrisHines Yep. This is the one I was trying to fix. Forgot to close the issue. :) Thanks!
