### ISSUE TITLE
Corrupted database file when system crashes

### ISSUE THREAD

**Issue by uronce-cc** [boltdb/bolt#514]
If power outage happens when executing [this line of code](https://github.com/boltdb/bolt/blob/master/tx.go#L502), then maybe part of the buffer is written to the file, so the database file is left in a corrupted state.

I don't quite understand the [description here](https://github.com/boltdb/bolt/blob/master/doc.go#L9) saying that no recovery is needed facing system crash, could someone explain your understanding of this issue and join the discussion? Thanks!

**Comment by xiang90** [comment]
boltdb has two metadata page at the beginning. They have magic number and checksum protected. boltdb only writes one meta page at a time for a write txn. If it crashes during the write, it can recover from the previous one.

**Comment by uronce-cc** [comment]
@xiang90 Thanks for the explanation! I've got the idea.
