### ISSUE TITLE
Corrupted data in Bolt DB

### ISSUE THREAD

**Issue by leadinglocally** [boltdb/bolt#519]
When I run my go program, it downloads a lot of JSON and stores it in Bolt. The 2nd time I run my program it reads all of the data in from the SSD. The third time I run my program, the data is now corrupted. Any idea what is going on?

Example corruption (seems to include key and value and is incomplete)

��
  �BJ5KbUQ_MxQzVwTZC81GiLDiYgRQHY{"!":{"input":{"U":"BJ5KbUQ_MxQzVwTZC81GiLDiYgRQHY","V":"household","C":1455806969406,"M":1455806969406},"lang":{"U":"BJ5KbUQ_MxQzVwTZC81GiLDiYgRQHY","V":"EN","C":1455806969358,"M":1455806969358},"origin":{"U":"BJ5KbUQ_MxQzVwTZC81GiLDiYgRQHY","V":"BJ5KbUQ_MAj9CWFAzLA4RLAhjSWKi4","C":1455806969464,"M":1455806969464}},"A":"BJ5KbUQ","C":1455806969299,"M":1455806969299,"N":"instance","X":"EN@B

**Comment by xiang90** [comment]
@leadinglocally It is not clear what happened. Can you please make it clear what is the original input, and what is the corrupted output? How do you know this is a blotdb issue?

Moreover, can you reliably reproduce this issue?

**Comment by leadinglocally** [comment]
Thanks for your prompt response, The original input was just a JSON file smaller than 1 kilobyte.

I'm pulling the JSON files from google storage and storing them in BoltDB so I never have to download them again. All the JSON is parsed first into an in-memory data structure, then written to Bolt.

To retrieve the JSON files, I'm using this function, then passing the bytes output to json.Unmarshal

```go
func (table *PolyGraphTable) GetBackup(fn string, bucketName []byte, backupName string) (bool, []byte) {
	fn += "/GetBackup"
	for {
		var b []byte
		table.poly.boltDB.View(func(tx *bolt.Tx) error {
			bucket := tx.Bucket(bucketName); if bucket == nil { panic("MISSING BUCKET: "+table.ID) }
			b = bucket.Get([]byte(backupName))
		    return nil
		})
		if b == nil { break }
		return true, b
	}
	return false, nil
}
```

Once the files are written they are never modified. The key for the below entry is BJ5KbUQ_MxQzVwTZC81GiLDiYgRQHY, and you can see in the first line that the key is being output before the start of a JSON file which is cut off at the end.

`��
�BJ5KbUQ_MxQzVwTZC81GiLDiYgRQHY{"!":{"input":{"U":"BJ5KbUQ_MxQzVwTZC81GiLDiYgRQHY","V":"household","C":1455806969406,"M":1455806969406},"lang":{"U":"BJ5KbUQ_MxQzVwTZC81GiLDiYgRQHY","V":"EN","C":1455806969358,"M":1455806969358},"origin":{"U":"BJ5KbUQ_MxQzVwTZC81GiLDiYgRQHY","V":"BJ5KbUQ_MAj9CWFAzLA4RLAhjSWKi4","C":1455806969464,"M":1455806969464}},"A":"BJ5KbUQ","C":1455806969299,"M":1455806969299,"N":"instance","X":"EN@B`

I can reproduce this issue very reliably, it happens the 2nd time (and onwards) after booting the server when the server has a fully stocked database. The first time it is able to read in the data, but it seems that it is being corrupted during this initial read.

**Comment by gyuho** [comment]
Any chance that the data was corrupted before you write to boltdb? (corrupted when you download from Google data storage)

**Comment by MJDSys** [comment]
@leadinglocally I see one issue off the bat: you can't access a byte array returned from bolt after you close a transaction.  In your code, you get the value at the key, which is fine.  But you then access this byte array after you've called View, which has closed the transaction.  At this point you could have anything returned.

You can either:

1.  Copy the byte slice to a new slice, which you can then access as much as you want afterwards.  Depending upon your use case, this might be the simplest, but at the cost of using and freeing memory quickly, causing the garbage collector to run more often.
2.  Decode the JSON inside the function you pass to View.  This is what I personally do, as it avoids the unnecessary copy.

I don't know if that will fix your issue, but I suggest you try that first.  That might fix it, or help surface the real bug.

**Comment by leadinglocally** [comment]
It seems I am writing the data back to bolt after unmarshalling it, because I dont yet have a switch to skip writing the JSON if it already was existing in the database, rather from GS.

As you say I must be writing back a corrupted version. Thanks for the advice.

**Comment by xiang90** [comment]
@leadinglocally I agree with @MJDSys

**Comment by leadinglocally** [comment]
seems to be solved, thanks for the great support

```go
func (table *PolyGraphTable) GetBackup(fn string, bucketName []byte, backupName string) (bool, map[string]interface{}) {
	fn += "/GetBackup"
	for {
		m := map[string]interface{}{}
		err := table.poly.boltDB.View(func(tx *bolt.Tx) error {
			bucket := tx.Bucket(bucketName); if bucket == nil { panic("MISSING BUCKET: "+table.ID) }
			err := json.Unmarshal(bucket.Get([]byte(backupName)), &m)
			if err != nil { return err }
		    return nil
		})
		if err != nil { break }
		return true, m
	}
	return false, nil
}
```
