### ISSUE TITLE
request for bitmap index operations

### ISSUE THREAD

**Issue by tvmaly** [boltdb/bolt#521]
is there a way to support bitmap index and operations like AND, OR, etc.  I am looking for a way to use bitmaps where each bit represents some id.  This is very useful for analytics, searching on features etc.  Right now I end up using either Redis http://redis.io/commands/bitpos  bit operations or I store roaring bitmaps in bolt and have to extract and instantiate them to perform the operations.   I am looking for a more direct way of doing these types of operations.

**Comment by benbjohnson** [comment]
@tvmaly There's no support for bitmap operations in Bolt (and it's outside the scope of Bolt as a key/value database).

You could split out the roaring bitmaps to store their containers as bolt key/values where the key is the 16-bit container id and the key is either the container's array or bitmap. That would give you fast look ups without needing to deserialize the entire roaring bitmap.
