### ISSUE TITLE
Please add note about use of Go's RFC3339Nano format

### ISSUE THREAD

**Issue by erock2112** [boltdb/bolt#536]
The README suggests the use of RFC3339 as a sortable time format for BoltDB keys: https://github.com/boltdb/bolt/blob/master/README.md#range-scans

Please add a note explaining that, while RFC3339 format is sortable, Go's RFC3339Nano format does not use a fixed number of digits after the decimal and is therefore not sortable.  This causes some subtle bugs for timestamps which are close together.  I'm hoping adding a note to that effect will prevent others from scanning the docs, seeing the suggestion to use RFC3339 for keys and assuming that RFC3339Nano will work as well.

**Comment by benbjohnson** [comment]
@erock2112 Can you submit a PR with the suggested change?
