### ISSUE TITLE
[enhancement] TTL on key

### ISSUE THREAD

**Issue by exu** [boltdb/bolt#541]
It would be great if bolt would have a possibility o set TTL on given key.

**Comment by xiang90** [comment]
I believe this is out of the scope of boltdb. boltdb should be a simple and "low level" engine. Probably user can implement TTL keys pretty simply by maintaining a TTL heap.

**Comment by benbjohnson** [comment]
@exu I agree with @xiang90. Bolt has a limited scope and is largely closed to additional enhancements. If you need TTL at a very low-level then I would suggest forking the project and adding it. Let me know if you have any questions about the internals!
