### ISSUE TITLE
Count items in bucket

### ISSUE THREAD

**Issue by rumkin** [boltdb/bolt#554]
How to count items in the bucket?

**Comment by benbjohnson** [comment]
There is no built-in counter on the bucket so you have to iterate over all items using a cursor.

**Comment by DavidVorick** [comment]
I thought you could use bucket.Stats().KeyN ?

**Comment by benbjohnson** [comment]
@DavidVorick That'll only work if you don't use nested buckets within that bucket. Otherwise it'll include all those keys as well.

**Comment by scbizu** [comment]
@benbjohnson I once used `bucket.Stats().KeyN` ,but after I use `cursor.Delete()` to remove a key-pair from bucket ,the output shows that the result of `KeyN`  do not have any change ....I wonder if my `delete` function do not work or it is the characteristic of `KeyN` ? And the best practice of  getting the number of my key-pairs is iterating over all of my key-pairs?
