### ISSUE TITLE
bolt uses host endianness when writing magic

### ISSUE THREAD

**Issue by cyphar** [boltdb/bolt#558]
Comparing two `.db` files from different architectures, it's clear that the host endianness is used when storing (and checking) the `magic` value `0xED0CDAED`:

```
% xxd -s +16 -l 4 s390x.db
00000010: ed0c daed                                ....
% xxd -s +16 -l 4 amd64.db
00000010: edda 0ced                                ....
```

This causes issues with `bolt check` as well as actually loading the database. This makes it very hard to actually debug `boltdb` issues.

**Comment by benbjohnson** [comment]
Host-specific endianness is a design decision carried over from LMDB and it exists throughout the codebase. It'd be nice to have a single endianness used but unfortunately it's too large of a change (and a breaking change) that probably wouldn't benefit most users.

There's some documentation in [Caveats & Limitations](https://github.com/boltdb/bolt/blob/master/README.md#caveats--limitations) regarding endianness:

> The data structures in the Bolt database are memory mapped so the data file will be endian specific. This means that you cannot copy a Bolt file from a little endian machine to a big endian machine and have it work. For most users this is not a concern since most modern CPUs are little endian.

**Comment by cyphar** [comment]
It could be done transparently by checking what the byte order of the magic is in the file, if we *really* wanted to stick with different database layouts on different architectures (I'm ignoring that this is not a good idea in either case).

**Comment by benbjohnson** [comment]
True, we could do it transparently. I haven't seen anyone else raise this as an issue though so I'm hesitant to make sweeping code changes. We can leave this issue here and if others have an interest in seeing this functionality added then we can do it.

**Comment by mkobetic** [comment]
Is it doable without significant overhead though? You'd probably want to optimize for the common case of matching host and db endianness, but it would probably have some overhead even in that case (checking some sort of `need to swap bytes` flag wherever we're dealing with multi-byte values). Moreover, given that values are just bytes with embedded payload, users will often still need to deal with it themselves at that level. Not sure the cost/benefit ratio is low enough here.

**Comment by benbjohnson** [comment]
@mkobetic Yeah, I agree. You could have functions attached to the DB that convert based on the database endianness vs host endianness but even then you'll incur function invocation overhead since they can't be inlined at compile time.

**Comment by cyphar** [comment]
@mkobetic If you use `endian(3)` and family, you can do it on a per-integer basis. They already optimise for the case where the host endianness is the target byte order. Strings work perfectly fine (they're single byte) so we just have to deal with metadata. As long as it's clear that it's a compatibility mode the "significant overhead" (which I don't think will be that significant, since the amount of time taken to flip the endianness shouldn't be on the order of magnitude of `fsync()` and writes) wouldn't be that bad.

**Comment by mkobetic** [comment]
I'd assume that `binary.ByteOrder` offers the same capabilities. I don't know that there will be "significant overhead", but I am concerned. Note that it's not just write overhead, but read overhead as well. Every time you navigate down the page tree (every step of a Cursor), you'll be decoding pgids and pointers over and over again. Small things can add up if there's enough of them.

**Comment by cyphar** [comment]
I might write a converter between endianness for `bolt` because I really need to be able to debug issues that happen on big endian systems locally.

**Comment by benbjohnson** [comment]
A converter is a good idea. The file format is stable and its relatively simple. There's no crazy bit packing or compression involved. There's just a few different page types.
