### ISSUE TITLE
bolt.Open with options hangs

### ISSUE THREAD

**Issue by alexdeefuse** [boltdb/bolt#562]
Hi,

I'm trying to use the store inside a linux VM (Vagrant with NFS).
The bolt.Open hangs indefinitely even if I supply a timeout.

```
db, err := bolt.Open("store.db", 0600, &bolt.Options{
    Timeout: 1 * time.Second,
})
if err != nil {
    log.Fatal(err)
    return
}
defer db.Close()

```

I've looked at the code and the problem seems to be with:

`err := syscall.Flock(int(db.file.Fd()), flag|syscall.LOCK_NB)`

Inside "boltdb/bolt/bolt_unix.go" in the "flock" function.

Any ideas on how to correct this?

Thanks,
Alex

**Comment by benbjohnson** [comment]
@alexdeefuse A couple questions:

1. Do you have another process that is also opening `store.db`?
2. Does it work on the local VM file system (aka not across NFS)?
3. Does it work outside the VM on your local system?

It does seem strange that the timeout is not triggering.

**Comment by alexdeefuse** [comment]
Hi,

Thanks for your reply. Very brief answers:

1. No other process that I'm aware of
2. No it doesn't
3. Didn't try that

A few more details about the scenario where I've noticed this:

I have my host environment (the actual machine) that doesn't have Go installed at all. It's a bare linux machine with Virtual Box and Vagrant and it uses NFS to share the Go folders with the guest machine.
The guest machine has a Go development environment.

The database file (store.db) is created inside the VM environment by a very basic go app. The database file is stored in a path that is under NFS.

I will try to store the db file in a non-NFS path and get back to you.

Best,
Alex

**Comment by alexdeefuse** [comment]
I can confirm that placing the database file outside of NFS has fixed the issue.
