### ISSUE TITLE
[Question] Retrieving a random key

### ISSUE THREAD

**Issue by jinks** [boltdb/bolt#572]
Hi,

I have a rather strange requirement. I have a data structure that boils down to a map[string][]string, usually something that would fit nicely into a boltdb. My problem: For some operation I need to get a random element from that map as a starting point.

As far as I can tell the only way to do that in boltdb is to iterate over all the keys, stick them in a []string and then choose a random one from that to b.Get(). Holding the whole array of keys in memory is not something I necessarily want to do. Is there anything I'm missing to make this more efficient?

**Comment by benbjohnson** [comment]
There's not currently a way to retrieve a random key from a bucket. If you keep track of the number of keys in the bucket you could use `math/rand.Intn()` to determine an index and then use a cursor to iterate up to that key.

If your data is too large for that you could maintain a histogram of your data and jump to a section of your bucket from a known key using `Seek()` and then iterate from there.
