### ISSUE TITLE
Оptimal remove old range

### ISSUE THREAD

**Issue by deepch** [boltdb/bolt#575]
Your base is very fast and excellent but lacks documentation.
I use a lot Bucket and date key RFC3339

but I have no idea how to delete all records older than 30 days

for all Bucket ?
   delete range?

please tell me how it can be implemented

**Comment by benbjohnson** [comment]
You can use a `Cursor` from the bucket to iterate and delete. Something like:

```go
// Compute 30 days ago.
start := time.Now().AddDate(0, 0, -30)

// Determine key to start from.
seek := []byte(start.Format(time.RFC3339))

// Iterate over bucket starting from your initial key.
c := bkt.Cursor()
for k, _ := c.Seek(seek); k != nil; k, _ := c.Next() {
	if err := c.Delete(); err != nil {
		return err
	}
}
```

**Comment by deepch** [comment]
It is perfectly thx!

But what if I do not know the names of all Bucket
possible to get them in a cycle?

sample
// Compute 30 days ago.
start := time.Now().AddDate(0, 0, -30)

// Determine key to start from.
seek := []byte(start.Format(time.RFC3339))

	for _, bkt := range db.BucketList() {
		for k, _ := c.Seek(seek); k != nil; k, _ := c.Next() {
                    if err := c.Delete(); err != nil {
                        continue
                    }
                }
	}

**Comment by benbjohnson** [comment]
You can determine if a key points to a nested bucket if `v == nil` during cursor iteration. Then you can call `Bucket(k)` to retrieve the bucket.
