### ISSUE TITLE
Risk of panic?

### ISSUE THREAD

**Issue by rgeronimi** [boltdb/bolt#576]
This is not a bug report but a question/suspicion about a potential one.

The doc states a good use policy: 
"Keys and values retrieved from the database are only valid for the life of the transaction. When used outside the transaction, these byte slices can point to different data or can point to invalid memory which will cause a panic. »

So here is a potential scenario where a panic may (in theory) occurs:

```
func (…) … {
	…
	tx, err := t.boltdb.Begin(false)
	if err != nil {
		…
	}
	b := tx.Bucket("test")
	if b == nil {
		…
	}
	value := b.Get(key)
	…
	if err := tx.Rollback(); err != nil {
		…
	}
	… (POINT A)
	return …
}
```

My worry is about point A above : at that point, even if the developper doesn’t use it anymore, value might still be allocated on the stack, e.g., due to a  compiler decision to keep the stack as it is until the end of the function. In such case, if a full garbage collection occurs right on that point, from what I understand of the Go garbage collector, a simplistic mark-and-sweep summary of its behavior is (but I know the GC is much more complex):
- All active goroutines are frozen
- All objects, starting from the root objects, are marked as used, and, when their fields contain pointers to other objects, explored recursively
- Root objects being the objects on the stack of the goroutines, which includes value
- So the pointer destination (the byte slice the library allocated in memory) behind value will be marked as used, which breaks the good use policy, with the potential consequences (panic, crash, with this version of boltdb or a future version).

Is that a possible outcome?
If yes, what can we prevent it?
If not, does that mean a compiler/native feature is used to prevent this issue from occurring?

**Comment by benbjohnson** [comment]
@rgeronimi Byte slices returned from Bolt just shouldn't be used after a transaction commits or rolls back. It's fine if the references exist in memory and are waiting for GC. It only matters if they are actually read from by your code at _Point A_.

Reading from the slice will attempt to read from the underlying mmap which either:

1. The file has been unmapped and you'll get a `SEGFAULT`

2. A new page has been written to where your byte slice points to and you'll be referencing different data.

The mmap is read-only so no data corruption can occur.
