### ISSUE TITLE
mmap cannot be turned off

### ISSUE THREAD

**Issue by panamafrancis** [boltdb/bolt#581]
I'd like to know if there's a way to load a large BoltDB database without having to mmap it.

The issue is that some of our windows machines have only 8GB of RAM, which is not upgradable and as a result of this they can't load large bolt databases.

I dug through the code and found that the initial map size option is ignored if less than the file size.
https://github.com/boltdb/bolt/blob/master/db.go#L257

what would be a feasible quick-fix i could implement?

Cheers!

**Comment by benbjohnson** [comment]
Is your Windows machine 32-bit or 64-bit? The mmap() will put the database into virtual memory but that is not limited to your physical RAM. The OS will page data in and out of physical RAM automatically. However, if you have a 32-bit machine then your virtual memory is limited to 2GB.

**Comment by panamafrancis** [comment]
It's a 64 bit machine running windows 10.

The returned error is:
"Not enough storage is available to process this command."


I'll have a look to see if i can replicate this in a unit test without boltdb, might be a Go problem.

**Comment by tv42** [comment]
Bolt without mmap would be a completely different library; direct reading is pretty much the point of the design.

Instead, this seems to be a question of how to get Windows mmap to behave sanely -- mmapping a terabyte-size *should* be completely doable, as mmap consumes virtual memory not physical. Searches seem to provide nothing of value, beyond a vague hint that memory fragmentation might be the cause: http://kb.tableau.com/articles/issue/error-not-enough-storage-is-available-to-process-this-command-refreshing-extract -- or that Windows might require that you have sufficient temp disk space to page out dirty pages (of a `PAGE_READONLY` mapping? derp).

**Comment by tv42** [comment]
Hrmm, http://stackoverflow.com/questions/726471/how-big-can-a-memory-mapped-file-be "at most 2GB minus [...]" sounds like https://www.youtube.com/watch?v=YxYvzVxJtYM

**Comment by panamafrancis** [comment]
Yup, you're right there's not much that can be done from bolts side to fix this kind of issue.

Our fix was to increase the amount of virtual memory available and turn it on and off again.
