### ISSUE TITLE
Boltdb does not support setting an expiration key?

### ISSUE THREAD

**Issue by Comdex** [boltdb/bolt#585]
If support, I can not find a api to set an expiration key?

**Comment by chrsm** [comment]
Bolt does not support automatically deleting records.

**Comment by Comdex** [comment]
Thanks. I think it can be improved.

**Comment by benbjohnson** [comment]
@Comdex Thanks for submitting an issue. Adding expiration would change the underlying file format and now that Bolt is post-1.0 it's format is fixed. Adding expiration also adds complexity and Bolt is meant to be a very low-level, basic data store. Expiration is certainly something that could be added at a higher level by another library or application wrapping Bolt.
