### ISSUE TITLE
degradation write rate

### ISSUE THREAD

**Issue by deepch** [boltdb/bolt#588]
I am using a bolt , but noted that the program began to hang heavy loads

fist im use sample

```
db.Update(func(tx *bolt.Tx) error {
    b := tx.Bucket([]byte("MyBucket"))
    err := b.Put([]byte("answer"), []byte("42"))
    return err
})

```
I thought that this is due to the large number of requests and made ​​an example
im write 400-500 record  sample pre 10 second call to UpdateAll

im use new blank db and sample code 

```
func (this *Database) UpdateAll(ra *AN) error {
	start := time.Now()
	tx, err := this.db.Begin(true)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	for _, vs := range ra.Samples {
		b, err := tx.CreateBucketIfNotExists([]byte(vs.stream))
		if err != nil {
			return err
		}
		err = b.Put([]byte(vs.time.Format(time.RFC3339)), vs.speed)
		if err != nil {
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	log.Println(time.Now().Sub(start))
	return nil
}

```
result
```

2016/08/31 02:48:18 111.949468ms 
2016/08/31 02:48:28 124.107977ms 
2016/08/31 02:48:38 129.874322ms 
2016/08/31 02:48:48 120.574788ms 
2016/08/31 02:48:59 146.964264ms 
2016/08/31 02:49:09 135.01402ms 
2016/08/31 02:49:19 160.893979ms 
2016/08/31 02:49:29 155.686818ms 
2016/08/31 02:49:39 196.514736ms 
2016/08/31 02:49:49 171.634565ms 
2016/08/31 02:50:00 202.887544ms 
2016/08/31 02:50:10 210.13193ms 
2016/08/31 02:50:20 213.920023ms 
2016/08/31 02:50:30 219.306351ms 
2016/08/31 02:50:41 229.614795ms 
2016/08/31 02:50:51 226.019675ms 
2016/08/31 02:51:01 225.920553ms 
2016/08/31 02:51:11 229.282451ms
2016/08/31 02:51:22 264.97258ms 
2016/08/31 02:51:32 253.032475ms 
2016/08/31 02:51:42 264.182403ms 
2016/08/31 02:51:52 271.827901ms 
2016/08/31 02:52:03 290.123409ms 
2016/08/31 02:52:13 281.201835ms 
2016/08/31 02:52:23 323.334891ms 
2016/08/31 02:52:34 286.121913ms 
2016/08/31 02:52:44 327.653549ms 
2016/08/31 02:52:54 292.658816ms 
2016/08/31 02:53:05 339.638336ms 
2016/08/31 02:53:15 312.893447ms 
2016/08/31 02:53:25 375.499314ms 
2016/08/31 02:53:36 329.039816ms 
2016/08/31 02:53:46 361.102988ms 
2016/08/31 02:53:57 339.556525ms 
2016/08/31 02:54:07 369.004557ms 
2016/08/31 02:54:17 338.763852ms 
2016/08/31 02:54:28 362.866005ms 
2016/08/31 02:54:38 392.435663ms 
2016/08/31 02:54:49 380.57226ms 
2016/08/31 02:54:59 392.717227ms 
2016/08/31 02:55:09 356.089117ms 
2016/08/31 02:55:20 389.930549ms 
2016/08/31 02:55:30 361.933965ms 
2016/08/31 02:55:41 408.527488ms 
2016/08/31 02:55:51 373.320177ms 
```

maybe I 'm doing something wrong , or it should not be ?

**Comment by benbjohnson** [comment]
@deepch Bolt will get slower as the size of the data increases, however, it should increase at a `log(n)` rate and your time seems to be increasing linearly:

<img width="357" src="https://cloud.githubusercontent.com/assets/118015/18148526/54022338-6f97-11e6-9418-c3cd18cb339a.png">

Can you provide a small, self-contained example Go program that replicates the issue? It's hard to tell what might be happening without having something that I can run locally.

**Comment by deepch** [comment]
there is not linear when the base is already large it is less noticeable.

my data sample

Bucket name {string 20 char} and data json {"s":"int(0-100000)", {"r":"int(0-100000)"}

at this point I mean result 450 recored insert to db (db size 402264K) 683.775366ms
 
I understand there linearly by file size 400mb =0.7 sec 4G = 7 sec ?

**Comment by deepch** [comment]
next test daemon uptime 9 hr db size 168552K daemon put group to db 400-500 record every 10 sec format 

I have forgiven the data to a minimum

k := make([]byte, 4)
binary.BigEndian.PutUint32(k, vs.speed)
err = b.Put([]byte(vs.time.Format(time.RFC3339)), k)

result speed 

```
2016/09/01 13:03:00 [DBQ] [INSERT] 697.971766ms
2016/09/01 13:03:11 [DBQ] [INSERT] 739.557726ms
2016/09/01 13:03:21 [DBQ] [INSERT] 669.715845ms
2016/09/01 13:03:32 [DBQ] [INSERT] 751.583574ms
2016/09/01 13:03:43 [DBQ] [INSERT] 693.752912ms
2016/09/01 13:03:54 [DBQ] [INSERT] 737.121834ms
2016/09/01 13:04:04 [DBQ] [INSERT] 686.236122ms

```

sample code


```
func (this *Database) UpdateAll(ra *AN) error {
	start := time.Now()
	tx, err := this.db.Begin(true)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	for _, vs := range ra.Samples {
		b, err := tx.CreateBucketIfNotExists([]byte(vs.stream))
		if err != nil {
			return err
		}
		k := make([]byte, 4)
		binary.BigEndian.PutUint32(k, vs.speed)
		err = b.Put([]byte(vs.time.Format(time.RFC3339)), k)
		if err != nil {
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	log.Println("[DBQ] [INSERT]", time.Now().Sub(start))
	return nil
}
```

tell this normal time insert ? I can test the approach week / month record

**Comment by benbjohnson** [comment]
@deepch Can you post a single Go file with data that I can run? The `UpdateAll()` function alone doesn't help me to test it.

**Comment by dtfinch** [comment]
If you're testing on a desktop/laptop (writing to a hard disk without a non-volatile write cache) you might be seeing sync delays as the OS waits for data to be written.

**Comment by deepch** [comment]
no i test server sas disk os ubuntu server 15
i write test and send this thread

**Comment by deepch** [comment]
Question can be closed. He reaches a certain value and keeps it for my system is 700 - 800 ms
