### ISSUE TITLE
Bug/Proposal: add support for jffs2 filesystem

### ISSUE THREAD

**Issue by WeiZhang555** [boltdb/bolt#592]
Recently I'm trying to run docker on jffs2 filesystem but found it failed on this line:

docker/docker:volume/store/store.go:75
``` 
vs.db, err = bolt.Open(dbPath, 0600, &bolt.Options{Timeout: 1 * time.Second})
```

I dug deeper and found that boltdb try to make use of the syscall `mmap`, but jffs2 has some problems on supporting mmap. I made a simple test program for illustrating the problem:

```test_jffs.go
package main

import (
        "fmt"
        "os"
        "syscall"
)

func main() {
        path := "/mnt/jffs2/volumes/metadata.db"
        var file *os.File
        var err error
        if file, err = os.OpenFile(path, os.O_RDWR|os.O_CREATE, 0600); err != nil {
                fmt.Printf("open failed: %s\n", err.Error())
        }

        _, err = syscall.Mmap(int(file.Fd()), 0, 32768, syscall.PROT_READ, syscall.MAP_SHARED)
        if err != nil {
                fmt.Printf("syscall map failed: %s\n", err.Error())
        }
}
```

It will report error: "syscall map failed: invalid argument"

`/mnt/jffs2` directory is a mountpoint of jffs2 filesystem.
```
# df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/mtdblock0    131072     8696    122376   7% /mnt/jffs2
```

Test result shows that if I replace `syscall.MAP_SHARED` with `syscall.MAP_PRIVATE`, everything works. For making `docker` work on jffs, I made a rough patch:

```
diff --git a/vendor/src/github.com/boltdb/bolt/bolt_unix.go b/vendor/src/github.com/boltdb/bolt/bolt_unix.go
index cad62dd..9180cbe 100644
--- a/vendor/src/github.com/boltdb/bolt/bolt_unix.go
+++ b/vendor/src/github.com/boltdb/bolt/bolt_unix.go
@@ -47,7 +47,7 @@ func funlock(db *DB) error {
 // mmap memory maps a DB's data file.
 func mmap(db *DB, sz int) error {
        // Map the data file to memory.
-       b, err := syscall.Mmap(int(db.file.Fd()), 0, sz, syscall.PROT_READ, syscall.MAP_SHARED|db.MmapFlags)
+       b, err := syscall.Mmap(int(db.file.Fd()), 0, sz, syscall.PROT_READ, syscall.MAP_PRIVATE|db.MmapFlags)
        if err != nil {
                return err
        }

```

But I think this will bring some kinds of problems, as that I'm not familiar with boltdb, can some guys from boltdb make a fix for this?  Maybe replace mmap with some other implementations.

Thanks!

**Comment by chrsm** [comment]
I think the issue with `MAP_PRIVATE` is that changes aren't replicated to the underlying file. Furthermore they're not shared with other processes using the same mapping, so I'd guess this would break bolt's "read-only" sharing mode.

**Comment by benbjohnson** [comment]
@WeiZhang555 I tried switching to `syscall.MAP_PRIVATE` and the tests break immediately. I'm not sure if it's because of the file descriptor being opened as read/write.

The mmap is pretty core to Bolt's implementation and switching out for pluggable implementations will affect stability.

**Comment by WeiZhang555** [comment]
I'm not saying we should simply replace `syscall.MAP_SHARED` with `syscall.MAP_PRIVATE`, just want to make some example codes to prove `syscall.MAP_SHARED` is the reason that boltdb can't support jffs2.

Is there any substitution for syscall.MAP_SHARED without influencing current stability?

**Comment by hjfreyer** [comment]
FYI, I just spent a while tracing a similar issue with the 9p filesystem down to this. It'd be nice if the documentation had a "supported filesystems" section.
