### ISSUE TITLE
boltdb flock fails on glusterfs 3.7.9

### ISSUE THREAD

**Issue by vrecan** [boltdb/bolt#600]
I attempted to run boltdb from multiple nodes on [glusterfs](https://gluster.readthedocs.io/en/latest/) and it immediately deadlocks. When switching to [FcntlFlock](https://golang.org/pkg/syscall/#FcntlFlock) it behaves as you would expect.

In golang we have run into issues with flock in our software, mostly around it's interaction with [glusterfs](https://gluster.readthedocs.io/en/latest/). The solution we ended up sticking with was using [FcntlFlock](https://golang.org/pkg/syscall/#FcntlFlock) instead. It's compatable with all standard filesystems and behaves well with [glusterfs](https://gluster.readthedocs.io/en/latest/). 

I would like to put up a pr to fix this, would you prefer that I just replace the current implementation or would you want an option to enable  [FcntlFlock](https://golang.org/pkg/syscall/#FcntlFlock)?

**Comment by benbjohnson** [comment]
There's an implementation with `FcntlFlock` in `bolt_solaris.go`. You can replace the `Flock()` implementation in `bolt_unix.go`, do some testing, and send a PR.

**Comment by vrecan** [comment]
I spent a few days testing the change and it functions correctly on glusterfs now. The one downside is that the current unit tests do not pass because FcntlFlock does not allow you to lock the same file from the same process because it's a process level lock. So I can't functionally write a unit tests without writing something that exec's another process that tries to lock it. Is it ok to just disable those tests or should I try and figure this out?
