### ISSUE TITLE
multiple connections to sinle boltdb file

### ISSUE THREAD

**Issue by alioygur** [boltdb/bolt#617]
I have multiple apps and I want to connect single boltdb file.

I know that bolt does not support multiple connections. I have and idea but I don't know this is good idea.

Currently, I am opening a connection and sharing this connection through app. I never close this connection.

```go
func main() {
    // Open the my.db data file in your current directory.
    // It will be created if it doesn't exist.
    db, err := bolt.Open("my.db", 0600, nil)
    if err != nil {
        log.Fatal(err)
    }
    defer db.Close()

    ...
}

func addUser(user interface{}, db *bolt.DB) error {
   return db.Save(user)
}
```

But if i use like this then i can use single db from multiple app instances

```go
func openConn() *bolt.DB{
    db, err := bolt.Open("my.db", 0600, nil)
    if err != nil {
        log.Fatal(err)
    }
    return db
}

func addUser(user interface{}) error {
   db := openConn()
   defer db.Close()
   return db.Save(user)
}
```

So what are you think about this approach? is this good or are there any performance issues

**Comment by benbjohnson** [comment]
That will certainly work but you'll have the overhead of mmapping and initializing the database on each `Open()`. That'll add some overhead but maybe it's not enough to be a problem. The best way to find out is to benchmark on the system you'll be deploying.
