### ISSUE TITLE
Timestamp/Value Storage Used in Bytes

### ISSUE THREAD

**Issue by louisto** [boltdb/bolt#623]
I'm using BoltDB to store timeseries data and found that the data I'm storing takes about 50 Bytes/Record. This is a bit more than I expected - how can I get this down?

From [this timeseries DB benchmark](https://cdn2.hubspot.net/hub/528953/hubfs/Screen_Shot_2016-08-27_at_00.32.42.png?t=1478549439172) it looks like InfluxDb (which I think at one point was running on BoltDB) can get down to 2.2 bytes per point.

Each record is:
(Key)Timestamp : (Value)[]byte("true")
timestamp := uint32(time.Date(2016, 1, 1, 0, 0, 0, 0, time.UTC).Unix())
key := make([]byte,8)
binary.BigEndian.PutUint32(key,timestamp)
after the write...timestamp++

With the above, I write 100,000,000 records in 240 seconds (416,667 recs/sec) and use about 5,000,000,000 bytes

bolt stats gives me:
Aggregate statistics for 1 buckets

Page count statistics
	Number of logical branch pages: 14874
	Number of physical branch overflow pages: 0
	Number of logical leaf pages: 1234567
	Number of physical leaf overflow pages: 0
Tree statistics
	Number of keys/value pairs: 100000000
	Number of levels in B+tree: 5
Page size utilization
	Bytes allocated for physical branch pages: 60923904
	Bytes actually used for branch data: 30224544 (49%)
	Bytes allocated for physical leaf pages: 5056786432
	Bytes actually used for leaf data: 2519753072 (49%)
Bucket statistics
	Total number of buckets: 1
	Total number on inlined buckets: 0 (0%)
	Bytes used for inlined buckets: 0 (0%)

**Comment by louisto** [comment]
Setting bucket.FillPercent = .95 brought my usage down to 28 bytes per record.

Any way to get this even lower?

**Comment by charl** [comment]
@louisto did you manage to find some way to reduce the data or did you end up selecting a different db technology for your time series storage?
