### ISSUE TITLE
Binary search on retrieval

### ISSUE THREAD

**Issue by libeclipse** [boltdb/bolt#652]
Since keys are added in byte order, a binary search would work, and it'd be insanely efficient (O(log n) as opposed to O(n)).

Is there already a function for this that I'm missing, and if not, is there a chance of this being implemented?

**Comment by benbjohnson** [comment]
@libeclipse The `Cursor` is used to lookup data and it uses a binary search: https://github.com/boltdb/bolt/blob/master/cursor.go#L252

**Comment by libeclipse** [comment]
@benbjohnson Sorry if this is obvious, but I'm not sure how I'd use that method. The closest documented thing that I can find is `Seek()`, but its behaviour when it doesn't find a key isn't appropriate for my use.

**Comment by libeclipse** [comment]
@benbjohnson Not sure if I'm understanding this correctly.

So a binary search searches an ordered list for a distinct value, right? So what the `Seek()` function should do is take a single byte slice as an input, perform a binary search on the contents, and return that entry. If it cannot locate the input key, then it should return a nil.

If it does do that, I think it should be re-worded as the current docs are misleading. However, if it doesn't do that and instead, when it cannot find the input key it returns the next key in the database, the documentation is pretty accurate and I think that the Seek() function is not useful for my purpose. In this case, could you recommend a method to to the former aforementioned task, i.e. a standard binary search.
