### ISSUE TITLE
Mechanics of the Seek() function

### ISSUE THREAD

**Issue by libeclipse** [boltdb/bolt#655]
Related to #652

I'm not sure if I'm understanding the Seek() function properly.

So a binary search searches an ordered list for a distinct value, right? So what the Seek() function should do is take a single byte slice as an input, perform a binary search on the contents, and return that entry. If it cannot locate the input key, then it should return a nil.

If it does do that, I think the documentation should be re-worded as how it's currently phrased is misleading. However, if it doesn't do that and instead, when it cannot find the input key it returns the next key in the database, the documentation is pretty accurate and I think that the Seek() function is not useful for my purpose.

In this case, could you recommend a method to perform a simple binary search, without the functionality of the seek function when it cannot find a key? Or at least a way to ascertain if, when the seek() function finds a key, if it's the correct one or if it's just grabbed the next one in the database.

**Comment by vincent-petithory** [comment]
Indeed Seek() will not return nil, unless that makes the cursor be after the last key of the bucket.
If your use-case is to search for an *exact* key, Bucket.Get() is what you want : it will return nil if that key isn't found.
If you want to search by prefix, then check the key you get from seek is correct, e.g.:

```go
k, v := b.Seek([]byte("a.b.") 
if !bytes.HasPrefix(k, []byte("a.b.")) {
...
}```

**Comment by libeclipse** [comment]
@vincent-petithory Cheers for the response. Does `Bucket.Get()` do a normal iteration or a binary search?

**Comment by vincent-petithory** [comment]
yes, its implementation uses seek().
