### ISSUE TITLE
Is it OK than DB.Sync() is not protected with mutex?

### ISSUE THREAD

**Issue by vitalyisaev2** [boltdb/bolt#664]
I have to put the database into ```NoSync``` mode in order to achieve good write performance. Can ```DB.Sync()``` be used from a distinct goroutine with regard to possibly ongoing write transactions? Is it safe?

**Comment by benbjohnson** [comment]
`NoSync` isn't safe regardless of how you use it. I suppose syncing between write transactions would be more safe than randomly syncing from a separate goroutine but neither way is completely safe.

With regards to the race detector, running `DB.Sync()` from a separate goroutine should be fine.

**Comment by vitalyisaev2** [comment]
@benbjohnson thanks for clarification, it's very frustating that there is no safety guarantee for ```NoSync```. I have to switch syncing off because the performance of ```Sync``` mode for my use-cases and hardware (spinning HDD) is limited with only 200 RPS.
