### ISSUE TITLE
Q: efficient append?

### ISSUE THREAD

**Issue by glycerine** [boltdb/bolt#671]
I'm storing a large []byte blob in bolt.

I would like to efficiently append to the end of this blob.

I would like to append without having to read and write all the previously written megabytes of blob.

The entirety of the blob should be available when reading from its key.

Is this possible in Bolt?

**Comment by glycerine** [comment]
Doesn't look like append is available.

**Comment by adamluzsi** [comment]
@glycerine how about creating a bucket under the specified key and "append" by Puting new values under the NextSequence ID and when the whole content required, ForEach on the bucket and create an appended byte slice from it ?
