### ISSUE TITLE
request: compaction api call (as bolt disk space consumption grows without bound)

### ISSUE THREAD

**Issue by glycerine** [boltdb/bolt#674]
I don't mind that a bolt file takes up 3-4x the space on disk as the contained value, but I had a bug where my usually 500KB blob ballooned to 7MB before I caught the leak.

Now my boltdb takes up 21MB instead of the 1.5MB, which costs alot as I ship the file around.

Feature request: an api call to compact an existing boltdb file so that it takes up only the pages that are actually in use.  I suppose I could just delete and re-write the file from scratch, but that introduces a bunch of race conditions that could have the file disappearing if the process is killed at the wrong moment. 

Would this be difficult to implement?

**Comment by adamluzsi** [comment]
+1

**Comment by DavidVorick** [comment]
A really basic tool would open up the old bolt database, open up a new bolt database, then copy all the buckets + data over. This would probably result in significant compaction for your database.

**Comment by vincent-petithory** [comment]
There is the bolt compact for this, but it's offline.

Le mer. 12 avr. 2017 08:28, David Vorick <notifications@github.com> a
écrit :

**Comment by glycerine** [comment]
Apparently Go's os.Rename() provides atomic file rename, even on windows now[1], so I may try to implement this using the 

a) write out a whole new file
b) os.Rename the new file to the old file in place.

strategy.

[1] https://github.com/golang/go/issues/8914

**Comment by glycerine** [comment]
@vincent-petithory thanks for mentioning `bolt compact`, I'm looking at that code as an example.

I see an important concern is running out of memory if transactions aren't committed often enough.

https://github.com/boltdb/bolt/blob/master/cmd/bolt/main.go#L1620

where it says

> func (cmd *CompactCommand) compact(dst, src *bolt.DB) error {
> // commit regularly, or we'll run out of memory for large datasets if using one transaction.

As I have some large blobs myself, and I don't want to truncate them, I wonder if there is a way to get the size of the values without reading them, so I know if my transaction has enough space left in memory.... that or an atomic append (c.f. https://github.com/boltdb/bolt/issues/671) would be useful in getting a copy done efficiently. I suppose I could just make every value transfer a new transaction, but that seems like a recipe for an fsync storm.

**Comment by glycerine** [comment]
@benbjohnson: quick question: inside a read transaction, is there a way to get the size of a value without actually reading that value? Use: in order to avoid going over available memory limit when copying a database.

**Comment by xiang90** [comment]
> a) write out a whole new file
b) os.Rename the new file to the old file in place.

**Comment by glycerine** [comment]
Hi Xiang, the database uses 21MB of pages (file size on disk), but only 500KB of that is the actual data value. When writing out to a completely new database file, at first the file will only contain 500KB. When that 500KB is written again, the file will grow to 2*500KB. When the file is written with the one 500KB blob multiple times, it will expand to about 3-4 * 500KB or around 1.5-2MB. Compared to 21MB, the 2MB is compact.

**Comment by xiang90** [comment]
@glycerine  

from my experience with bolt, what usually causes the amplification is actually fragmentation. so we will have empty pages, half-written pages in between. simply rewriting the entire file at physical layer wont really help that much, we probably need to rewrite the db from the logic layer in seq order with a high enough filling percentage to defrag to compact.

**Comment by glycerine** [comment]
@xiang90 

> rewrite the db from the logic layer

Why ouldn't opening a whole new file, and writing to it, suffice to be a logic layer write?

After all, this is exactly what the current`bolt compact` code does. 

See https://github.com/boltdb/bolt/blob/master/cmd/bolt/main.go#L1558 and the following function, compact() at https://github.com/boltdb/bolt/blob/master/cmd/bolt/main.go#L1619

**Comment by xiang90** [comment]
https://github.com/boltdb/bolt/blob/master/cmd/bolt/main.go#L1619 is a logic rewrite. it is not simply a file level copy or write out. it is a rewrite at boltdb level. maybe i misunderstood your original proposal.

**Comment by glycerine** [comment]
> is there a way to get the size of a value without actually reading that value?

Answering my own question: The value slice pointing to the value bytes is unlikely to be a copy; so take len() of that should be fine to determine if there is memory space left to make the copy.

**Comment by glycerine** [comment]
@xiang90 I see where the confusion over "write a file" came from. I'm adapting the logic rewrite of the `bolt compact` command, making it into an api call.

**Comment by glycerine** [comment]
Wow. I put this on the backshelf because 3-4x was tolerable. But after running for longer, I'm now seeing 20x space consumption. My actual data is 465K. The space taken on disk is 11MB. Will probably have to pick this up again.

**Comment by glycerine** [comment]
It was very straight forward to use the bolt command's compaction from main.go for my application. 

https://github.com/glycerine/hnatsd/blob/master/peer/compact.go

This seems to work quite well. I'm going to let it run for a few days to make sure it works smoothly, before doing a PR here.

How to test? I'm not sure how to artificially induce fragmentation early on -- would be needed in order to write a test that the compaction/defrag works, so if anyone knows how to induce that quickly, let me know.

**Comment by glycerine** [comment]
#679 was proposed and declined. Closing this as won't fix.

I've made a fork that merges that fix. It supports compaction/big values. See https://github.com/bigboltdb/bolt.
