### ISSUE TITLE
db.Put() replace item?

### ISSUE THREAD

**Issue by DeadNumbers** [boltdb/bolt#678]
I'm trying import csv to bolt
```Go
package main

import (
	"github.com/boltdb/bolt"

	"bufio"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
)

var (
	inputfile string
	outfile   string
	delimiter string
	view      bool
)

func main() {
	flag.BoolVar(&view, "v", false, "-")
	flag.StringVar(&inputfile, "i", "", "input file")
	flag.StringVar(&outfile, "o", "out.boltdb", "out file")
	flag.StringVar(&delimiter, "d", "|", "delimiter")
	flag.Parse()

	if view {
		view_()
		os.Exit(0)
	}

	if err := csv2bolt(outfile, inputfile, delimiter, "TESTBUCKET"); err != nil {
		log.Fatal(err)
	}
}

func csv2bolt(db, input, delimiter, bucket string) error {
	if input == "" {
		return errors.New("Empty file")
	}

	f, _ := os.Open(input)
	scanner := bufio.NewScanner(f)
	counter := 0
	var header []string
	for scanner.Scan() {

		if counter == 0 {
			header = strings.Split(scanner.Text(), delimiter)
			counter++
			continue
		}
		line := strings.Split(scanner.Text(), delimiter)
		if len(line) < 2 {
			return errors.New("Item to short")
		}
		if len(line) != len(header) {
			//continue //uncomment to skip invalide lines
			return errors.New(fmt.Sprintf("len(%d) != len(%d)\n", len(header), len(line)))
		}

		for k, _ := range line {
			//debug
			fmt.Printf("Insert into %s KEY:%s, VALUE:%s\n", bucket, header[k], line[k])
			//end debug
			err := insert(db, bucket, header[k], line[k])
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func insert(s, b, k, v string) error {
	db, err := bolt.Open(s, 0644, nil)
	if err != nil {
		return err
	}
	defer db.Close()
	err = db.Update(func(tx *bolt.Tx) error {
		bucket, err := tx.CreateBucketIfNotExists([]byte(b))
		if err != nil {
			return err
		}
		err = bucket.Put([]byte(k), []byte(v))
		return err
	})
	return err
}

func view_() {
	db, _ := bolt.Open(outfile, 0644, nil)
	db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket([]byte("TESTBUCKET"))
		v := b.Get([]byte("id"))
		println("ID is:", string(v))
		return nil
	})
}
```

csv file
```
id|first name|last name|phone
1|user|userich|555-55-55
2|root|rootich|111-22-33
3|admin|adminich|555-55-55
4|other|otherich|123-45-67
5|test|nottest|000-00-00
```
After that, the last value remains in the database
>./csv2bolt -o test.db -v 
>ID is: 5

**Comment by nussjustin** [comment]
This is intended behaviour.

Each key is unique per bucket and has exactly 1 value. Using the same key twice, overrides the old value.

See the [Basics](https://godoc.org/github.com/boltdb/bolt#hdr-Basics) section in the [GoDocs](https://godoc.org/github.com/boltdb/bolt)

> There are only a few types in Bolt: DB, Bucket, Tx, and Cursor. The DB is a collection of buckets and is represented by a single file on disk. A bucket is a collection of **unique keys** that are associated with values.

[Bucket.Put](https://godoc.org/github.com/boltdb/bolt#Bucket.Put) is documented as

> Put sets the value for a key in the bucket. **If the key exist then its previous value will be overwritten**. Supplied value must remain valid for the life of the transaction. Returns an error if the bucket was created from a read-only transaction, if the key is blank, if the key is too large, or if the value is too large.

If you want to insert all records from your CSV file each record needs a unique key. If you have a column that is unique (for example an ID, as in your example) you could use this key. There is also [Bucket.NextSequence](https://godoc.org/github.com/boltdb/bolt#Bucket.NextSequence), which returns an autoincrementing integer that is tracked per bucket and can be used across program executions.

**Comment by DeadNumbers** [comment]
@nussjustin thanks for answer.

**Comment by adamluzsi** [comment]
@DeadNumbers try create buckets for each ID from the csv rows, and Put the content in that. Or if you could ignore the ID field and use NextSequence() that that's even better! :)

**Comment by DeadNumbers** [comment]
@adamluzsi  Yes, I try create buckets, where bucket name = `id`, but it's too slow to write, as it seemed to me. Also, I'm looking for the perfect storage format for data from my csv files, the average size of which is several (1-8) gigabytes. And BoltDB is just an attempt on this way :)

**Comment by adamluzsi** [comment]
@DeadNumbers Hy dead, this is just a sketch, but I made some adjustments on your sample code and changed a few parts to make the code optimized for BoltDB. I'm not a golang expert, just love this lang, so please don't be to hars on the code. 

First The Batch(func(*bolt.Tx) error) method allows you to work from multiple coroutines and this makes things pretty interesting. If we create some consumer based on the system CPU count, we can consume the the csv pretty fast, and insert values to the boltdb, while allowing the io writes to be optimised by the Batch *framework. This is especially good because opening and closing the db in every insert result in some throttling because the lot of io open/close between every insert. 

Further more using the csv lib we can remove some code (and tests) that we have to maintain, and use a little simplified form of consuming. 

this is just a raw sketch, but I try to present what my idea was to your problem when you want to achieve it with BoltDB.

```go
package main

import (
	"encoding/binary"
	"encoding/csv"
	"fmt"
	"io"
	"log"
	"runtime"
	"strings"
	"sync"

	"github.com/boltdb/bolt"
)

var ExampleCSV = `
id|first name|last name|phone
1|user|userich|555-55-55
2|root|rootich|111-22-33
3|admin|adminich|555-55-55
4|other|otherich|123-45-67
5|test|nottest|000-00-00
`

const MainBucketName = "test"

func main() {
	ioReader := strings.NewReader(ExampleCSV)

	db, err := bolt.Open(`test.db`, 0644, nil)

	if err != nil {
		log.Fatal(err)
	}

	r := csv.NewReader(ioReader)
	r.Comma = '|'

	headers, err := r.Read()

	if err != nil {
		log.Fatal(err)
	}

	ch := make(chan []string)
	var wg sync.WaitGroup

	for i := 0; i < runtime.NumCPU(); i++ {
		wg.Add(1)
		go consumer(&wg, headers, ch, db)
	}

	for {

		record, err := r.Read()

		if err == io.EOF {
			break
		}

		if err != nil {
			log.Fatal(err)
		}

		ch <- record
		fmt.Println(record)
	}

	close(ch)
	wg.Wait()
	log.Println("All done!")

}

func consumer(wg *sync.WaitGroup, headers []string, ch <-chan []string, db *bolt.DB) {
	defer wg.Done()

	for record := range ch {
		err := db.Batch(saveRecordTXBy(headers, record))
		if err != nil {
			log.Fatal(err)
		}
	}
}

func saveRecordTXBy(headers, record []string) func(*bolt.Tx) error {
	return func(tx *bolt.Tx) error {
		row, err := newBranch(tx)

		if err != nil {
			return err
		}

		return saveTo(row, headers, record)
	}
}

func saveTo(bucket *bolt.Bucket, headers, record []string) error {
	for i, value := range record {

		err := bucket.Put([]byte(headers[i]), []byte(value))

		if err != nil {
			return err
		}
	}

	return nil
}

func newBranch(tx *bolt.Tx) (*bolt.Bucket, error) {
	mainBucket, err := tx.CreateBucketIfNotExists([]byte(MainBucketName))

	if err != nil {
		return nil, err
	}

	ID, err := mainBucket.NextSequence()

	return mainBucket.CreateBucketIfNotExists(uintToByteSlice(ID))
}

// itob returns an 8-byte big endian representation of v.
func uintToByteSlice(v uint64) []byte {
	b := make([]byte, 8)
	binary.BigEndian.PutUint64(b, uint64(v))
	return b
}

```

I really love BoltDB and hope you @DeadNumbers find it likeable too ! : )
Happy coding!

**Comment by adamluzsi** [comment]
If you could define ID to be the first column in the psv (pipe separated vales :D) than NextSequence can be removed and ID could be used instead. Which would be batter for later on.

**Comment by DeadNumbers** [comment]
@adamluzsi Thank you for your attempt to help, but unfortunately it's all too slow.

**Comment by adamluzsi** [comment]
@DeadNumbers if your use case only to load fast and do some work with that, and not lot of fast read after an initial load, try some in memory db. :)

**Comment by DeadNumbers** [comment]
@adamluzsi сan I ask you some questions about boltdb in a different place? Suitable facebook or any messenger.

**Comment by adamluzsi** [comment]
@DeadNumbers sure, I try my best to answer your questions! :)

Skype (adamluzsi)
Hangouts (adamluzsi)
Facebook/Messanger  (adamluzsi)

**Comment by DeadNumbers** [comment]
@adamluzsi I send message to you in Facebook :)
