### ISSUE TITLE
document behaviour when a Bolt DB is copied mid-write

### ISSUE THREAD

**Issue by mappu** [boltdb/bolt#708]
Hi,

Sorry if this is already documented somewhere.

AFAICT Bolt does not have a WAL or journal. Is it "safe" to copy an in-use Bolt database?

i.e. if the database was being written to at the time of copy, will the resulting copied database read consistently from the old transaction?

Does the answer depend on whether a consistent filesystem snapshot was taken? (linux lvm2/zfs/btrfs snapshot or windows VSS snapshot)

Regards
mappu

**Comment by benbjohnson** [comment]
The only safe way to copy a Bolt database is to use [`Tx.WriteTo()`](http://godoc.org/github.com/boltdb/bolt#Tx.WriteTo). This ensures that a lock is obtained during the copy of the initial meta pages and it then ensures that pages for that transaction are not reused during the copy.
