### ISSUE TITLE
is there a way to replicate boltdb across multiple servers?

### ISSUE THREAD

**Issue by m-abdalrahman** [boltdb/bolt#710]
I built web service using boltdb, and I'm trying to make this service high availability,
but I don't know how I can replicate data between different servers,
is there a way to make me do that?

Thanks in advance.

**Comment by benbjohnson** [comment]
No, there's nothing in Bolt to support high availability. You'll need to add an additional layer at a higher level for that.

**Comment by vincent-petithory** [comment]
If you feel brave, you can give a try at [this lib](https://github.com/vincent-petithory/rbolt).
It's not an out-of-the-box solution but it provides some building blocks for what you want to achieve.
