### ISSUE TITLE
[RFE] Database Generation ID

### ISSUE THREAD

**Issue by obnoxxx** [boltdb/bolt#742]
For some purposes, it would be useful to have a database generation ID. This would be a UUID that would be generated and stored in the db when it gets initially created. During the lifetime of this DB file, it would never change. It would be possible to get the UUID with a method like GetDBGenerationID() or similar. This would be handy when doing dumps/backups, and restores of a db, to tell different incarnations apart. Together with the automatic Change Sequence Number proposed in #741, this would give a pretty complete picture of different states of the db.

**Comment by mendoncangelo** [comment]
@obnoxxx How can I contribute to this Issue? Please let me know if there is a guide to contributing.

**Comment by vincent-petithory** [comment]
This, along with #741, looks like it could be achieved with a simple
dedicated bucket for metadata. It is also quite app-specific and out of the
scope of implementing on boltdb imho.

Le mer. 24 janv. 2018 21:29, mendoncangelo <notifications@github.com> a
écrit :

**Comment by mendoncangelo** [comment]
@vincent-petithory Yes I would definitely like to contribute and open a PR with a metadata struct. Do you guys fork or prefer branches on the main repo?

**Comment by vincent-petithory** [comment]
As the author stated, boltdb is "frozen". I highly doubt such a PR will get
attention, especially since it looks like app specific. I think you're
better off forking and add what you need.

**Comment by mendoncangelo** [comment]
@vincent-petithory Thank you very much. I was looking for open source Go projects that I could contribute to. Do you know any interesting ones out there that encourage contributors to join?

**Comment by benbjohnson** [comment]
@mendoncangelo CoreOS has a a bolt fork that is maintained and accepts PRs: https://github.com/coreos/bbolt

However, I agree that this is app specific and probably isn't appropriate for such a low-level database.

**Comment by obnoxxx** [comment]
Thanks for the comments. While I don't think this is too app-specific, but tried to put it as a general feature of the DB, I do of course accept the statement that this is frozen, and we will implement our wrapper around boltdb that implements the generation ID with a metadata bucket.
