### ISSUE TITLE
how to use boltdb for multiple files 

### ISSUE THREAD

**Issue by qshuai** [boltdb/bolt#747]
If there is a single file to store, it will be so hug. I just want to store my data using many files. How to do this?

**Comment by igordata** [comment]
Just open as many as you want
`db1, err1 := bolt.Open("my1.db", 0600, nil)
db2, err2 := bolt.Open("my2.db", 0600, nil)`

**Comment by qshuai** [comment]
@igordata Thanks!

Your scheme is feasible， but I do not like the way! I am looking for the scheme better than this.

The following repository written by me is a sample similar to this scheme. 
[bolt-multifile-sample](https://github.com/qshuai/bolt-multifile-sample)
